image: node:23-bookworm

build:
  stage: build
  before_get_sources:
    - apt-get -qq update
    - apt-get -qqy install python3-venv wget unzip git
  before_script:
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install .
  script:
    - source .venv/bin/activate
    - wget --no-check-certificate "https://drive.google.com/uc?id=1tmS8xSTnhWWG5Nhqu1-Ue9Px9GFVVwO6&export=download"
    - mv "uc?id=1tmS8xSTnhWWG5Nhqu1-Ue9Px9GFVVwO6&export=download" Release_0_3_0.zip
    - unzip Release_0_3_0.zip
    - mv Release_0_3_0/\ hpm-fru-mockup\ v0.5.2.json Release_0_3_0/hpm-fru-mockup-v0.5.2.json
    - pnp-parser Release_0_3_0/hpm-fru-mockup-v0.5.2.json hpm-fru-mockup-v0.5.2-spec.json hpm-fru-mockup-v0.5.2-dataflow.json
  artifacts:
    expire_in: 4 week
    when: always
    paths:
      - hpm-fru-mockup-v0.5.2-spec.json
      - hpm-fru-mockup-v0.5.2-dataflow.json

deploy:
  stage: deploy
  tags: [docs]
  dependencies: [build]
  variables:
    GIT_STRATEGY: none
  script:
    - tar cf $CI_DOCS_ARCHIVE hpm-fru-mockup-v0.5.2-*.json
  artifacts:
    paths:
      - $CI_DOCS_ARCHIVE
