image: node:23-bookworm

build:
  stage: build
  before_get_sources:
    - apt-get -qq update
    - apt-get -qqy install python3-venv wget unzip git
  before_script:
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install .
  script:
    - source .venv/bin/activate
    - wget -O Release_0_5_0.zip "https://drive.google.com/uc?id=1HaQbhgrJ--7bkkTC8bfA2pGSGGwdEeJm&export=download"
    - unzip Release_0_5_0.zip
    - pnp-parser "Release_0_5_0/JSON Files/Mockups/HPM/hpm-fru-mockup-type1-hpm-example-v0.6.8.json" hpm-fru-mockup-v0.6.8-spec.json hpm-fru-mockup-v0.6.8-dataflow.json
  artifacts:
    expire_in: 4 week
    when: always
    paths:
      - hpm-fru-mockup-v0.6.8-spec.json
      - hpm-fru-mockup-v0.6.8-dataflow.json

deploy:
  stage: deploy
  tags: [docs]
  dependencies: [build]
  before_get_sources:
    - apt-get -qq update
    - apt-get -qqy install python3-venv wget unzip git
  before_script:
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install .
  script:
    - source .venv/bin/activate
    - pipeline_manager build static-html --single-html index.html hpm-fru-mockup-v0.6.8-spec.json hpm-fru-mockup-v0.6.8-dataflow.json --workspace-directory workspace --editor-title "$EDITOR_TITLE"
  after_script:
    - tar cf $CI_DOCS_ARCHIVE index.html
  artifacts:
    paths:
      - index.html
      - hpm-fru-mockup-v0.6.8-spec.json
      - hpm-fru-mockup-v0.6.8-dataflow.json
      - $CI_DOCS_ARCHIVE
