# generated by datamodel-codegen:
#   filename:  hpm-fru-mockup-v0.5.2.json
#   timestamp: 2025-06-02T21:49:19+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class BoardInfo(BaseModel):
    Type: str
    Subtype: str
    ManufacturingTimestamp: str
    Manufacturer: str
    ProductName: str
    SerialNumber: str
    PartNumber: str
    ModelNumber: str
    CountryOfOriginDesign: str
    CountryOfAssembly: str
    FRUFileID: str


class ProductInfo(BaseModel):
    ManufacturerName: str
    PartModelNumber: str
    Version: str
    SerialNumber: str


class Bus(BaseModel):
    Type: str
    Identifier: str


class PhysicalLocation(BaseModel):
    UpperXMils: int
    UpperYMils: int
    LowerXMils: int
    LowerYMils: int


class ConnectedBus(BaseModel):
    Type: str
    Identifier: str


class SoC(BaseModel):
    Identifier: str
    VendorName: str
    VendorID: str
    Type: str
    SilkscreenName: str
    ReferenceDesignator: str
    DimmChannelsSupported: int
    PhysicalLocation: PhysicalLocation
    ConnectedBuses: List[ConnectedBus]


class Slot(BaseModel):
    Identifier: str
    Proximity: str
    SilkscreenName: str
    ReferenceDesignator: str
    AssociatedSOC: str
    PhysicalLocation: PhysicalLocation
    ConnectedBuses: List[ConnectedBus]


class MemorySubsystem(BaseModel):
    Channels: int
    MemoryTechnology: str
    Slots: List[Slot]


class Composite(BaseModel):
    Identifier: str
    Type: str
    SilkscreenName: str
    ReferenceDesignator: str
    MPICs: List[str]
    MXIOs: List[str]
    PhysicalLocation: PhysicalLocation


class FlexIO(BaseModel):
    Identifier: str
    NetlistName: str


class Mxio(BaseModel):
    Identifier: str
    SOCSocketAssociation: str
    CommonClockingSupport: bool
    ConnectorType: str
    ConnectedBuses: List[ConnectedBus]
    SilkscreenName: str
    ReferenceDesignator: str
    FlexIOs: List[FlexIO]
    PhysicalLocation: PhysicalLocation


class Sideband(BaseModel):
    Identifier: str
    NetlistName: str


class Mpic(BaseModel):
    Identifier: str
    ConnectorType: str
    AdjustedMaximumActualPowerSupportedWatts: int
    SilkscreenName: str
    ReferenceDesignator: str
    Sidebands: List[Sideband]
    ConnectedBuses: List[ConnectedBus]
    PhysicalLocation: PhysicalLocation


class PowerSupply(BaseModel):
    Identifier: str
    ConnectorType: str
    SilkscreenName: str
    ReferenceDesignator: str
    HotPlugSupported: bool
    ConnectedBuses: List[ConnectedBus]
    PhysicalLocation: PhysicalLocation


class OCPMezzanineSlot(BaseModel):
    Identifier: str
    Version: str
    SilkscreenName: str
    ReferenceDesignator: str
    FormFactor: str
    ConnectedBuses: List[ConnectedBus]
    PairedSlotForDoubleWide: str
    PhysicalLocation: PhysicalLocation


class ControlPanel(BaseModel):
    Identifier: str
    SilkscreenName: str
    ReferenceDesignator: str
    Primary: bool
    ConnectedBuses: List[ConnectedBus]
    PhysicalLocation: PhysicalLocation


class PowerDistributionBoard(BaseModel):
    Identifier: str
    Type: str
    SilkscreenName: str
    ReferenceDesignator: str
    ConnectorType: str
    ConnectedBuses: List[ConnectedBus]
    PhysicalLocation: PhysicalLocation


class RealTimeClockBattery(BaseModel):
    Identifier: str
    SilkscreenName: str
    ReferenceDesignator: str
    PhysicalLocation: PhysicalLocation


class Fan(BaseModel):
    Identifier: str
    Pins: int
    MaximumPowerWatts: int
    ConnectorType: str
    SilkscreenName: str
    ReferenceDesignator: str
    HotPlugSupported: bool
    ConnectedBuses: List[ConnectedBus]
    PhysicalLocation: PhysicalLocation


class Sci(BaseModel):
    Revision: str
    Version: str
    CommonCircuitType: str
    BackupBatteryVoltageMeasurementCapable: bool
    ConnectedBuses: List[ConnectedBus]


class Connectors(BaseModel):
    SOCs: List[SoC]
    MemorySubsystems: List[MemorySubsystem]
    Composites: List[Composite]
    Mxios: List[Mxio]
    Mpics: List[Mpic]
    PowerSupplies: List[PowerSupply]
    OCPMezzanineSlots: List[OCPMezzanineSlot]
    ControlPanels: List[ControlPanel]
    PowerDistributionBoards: List[PowerDistributionBoard]
    RealTimeClockBatteries: List[RealTimeClockBattery]
    Fans: List[Fan]
    SCIs: List[Sci]


class HPM(BaseModel):
    VendorID: str
    DeviceID: str
    BoardInfo: BoardInfo
    ProductInfo: ProductInfo
    Buses: List[Bus]
    Connectors: Connectors


class Build(BaseModel):
    Version: str
    BuildTimestamp: str


class Version(BaseModel):
    Originator: str
    OriginalIPVersion: str
    ModifiedBy: str
    ModificationVersion: str
    ModificationTimestamp: str
    ModificationContact: str


class IPBlock(BaseModel):
    Identifier: str
    Type: str
    GUID: str
    Version: Version


class Bitfield(BaseModel):
    Identifier: str
    Type: str
    InstanceName: str
    LeastSignificantBit: int
    MostSignificantBit: int
    Reset: int
    Access: str


class Region(BaseModel):
    Identifier: str
    Name: str
    Version: str
    GUID: str
    OffsetBytes: int
    SizeBytes: int
    Bitfields: List[Bitfield]


class MemoryMap(BaseModel):
    Regions: List[Region]


class MappedInterface(BaseModel):
    Identifier: str
    Interface: str
    Offset: int
    Mapping: str
    Index: int
    Description: str


class VirtualWire(BaseModel):
    Identifier: str
    BitStart: int
    BitStop: int
    NetlistName: str
    Alias: str
    PhysicalWireAlias: str
    DefaultState: int
    ActiveState: int
    Access: str
    Direction: str
    Drive: str
    Polarity: str
    PowerStateValidMinimum: str
    MappedInterfaces: List[MappedInterface]


class FPGA(BaseModel):
    Model: str
    Manufacturer: str
    Build: Build
    IPBlocks: List[IPBlock]
    MemoryMap: MemoryMap
    VirtualWires: List[VirtualWire]


class ConnectedDevice(BaseModel):
    Endpoint: str
    SilkscreenName: str
    ReferenceDesignator: str


class DisplayPortItem(BaseModel):
    Identifier: str
    ConnectedDevices: List[ConnectedDevice]


class ESPIItem(BaseModel):
    Identifier: str
    HpmFpgaConnected: bool
    MaxClockSpeedMHz: int
    AlertUsage: str
    SecondaryChipSelect: bool
    Density: str
    ConnectedDevices: List[ConnectedDevice]


class BusVoltageSenseRange(BaseModel):
    HighVolts: int
    LowVolts: int


class OperatingVoltageRange(BaseModel):
    HighVolts: int
    LowVolts: int


class PackageSize(BaseModel):
    LengthTenthsMM: int
    WidthTenthsMM: int
    HeightTenthsMM: int


class Device(BaseModel):
    Identifier: str
    FrequencyMaxKHz: int
    Address: str
    Manufacturers: List[str]
    Models: List[str]
    PhysicalLocation: PhysicalLocation
    Description: str
    CapacityBytes: int
    ResolutionBits: int
    AccuracyHundredthsPercent: int
    BusVoltageSenseRange: BusVoltageSenseRange
    InputSupplyCurrentMaxAmps: int
    GpioCount: int
    OperatingVoltageRange: OperatingVoltageRange
    PackageType: str
    SilkscreenName: str
    ReferenceDesignator: str
    Pins: int
    PackageSize: PackageSize
    TotalPowerDissipationMilliWatts: int


class Channel(BaseModel):
    Identifier: str
    VoltageTenthsVolts: int
    IOType: str
    Endpoint: str


class Mux(BaseModel):
    Identifier: str
    Channels: List[Channel]
    PropagationDelayUS: int
    Address: str
    Manufacturers: List[str]
    Models: List[str]
    Description: str
    LevelShiftingCapable: bool
    FaultDetectionCapable: bool
    FaultClearSignalCapable: bool
    RiseTimeNS: int
    FallTimeNS: int
    PhysicalLocation: PhysicalLocation
    SilkscreenName: str
    ReferenceDesignator: str


class Bridge(BaseModel):
    Identifier: str
    Manufacturers: List[str]
    Models: List[str]
    Version: str
    SilkscreenName: str
    ReferenceDesignator: str
    LinkedBuses: List[str]


class Tree(BaseModel):
    Identifier: str
    Devices: List[Device]
    Muxes: List[Mux]
    Bridges: List[Bridge]


class I2CItem(BaseModel):
    Identifier: str
    VoltageTenthsVolts: int
    PowerState: str
    FrequencyKHz: int
    Description: str
    Trees: List[Tree]


class Device1(BaseModel):
    Identifier: str
    FrequencyMaxKHz: int
    Address: str
    Manufacturers: List[str]
    Models: List[str]
    Description: str
    SilkscreenName: str
    ReferenceDesignator: str
    PhysicalLocation: PhysicalLocation


class Port(BaseModel):
    Identifier: str
    Type: str
    VoltageTenthsVolts: int
    LDOEnabled: bool
    Group: int
    ReferenceVoltageTenthsVolts: int
    PullUpValueOhms: int
    DriverImpedanceOhms: int
    TargetPortMode: str
    PullUpEnabled: bool
    Endpoint: str
    Description: str


class Hub(BaseModel):
    Identifier: str
    Ports: List[Port]
    PropagationDelayUS: int
    Address: str
    Manufacturers: List[str]
    Models: List[str]
    SilkscreenName: str
    ReferenceDesignator: str
    Description: str


class Tree1(BaseModel):
    Identifier: str
    Devices: List[Device1]
    Hubs: List[Hub]


class I3CItem(BaseModel):
    Identifier: str
    ProtocolType: str
    VoltageTenthsVolts: int
    PowerState: str
    FrequencyKHz: int
    Description: str
    Trees: List[Tree1]


class Device2(BaseModel):
    Identifier: str
    PrimaryFPGA: bool
    SilkscreenName: str
    ReferenceDesignator: str
    Description: str


class Channel1(BaseModel):
    Identifier: str
    Endpoint: str
    Description: str


class MUX(BaseModel):
    Identifier: str
    Channels: List[Channel1]


class Tree2(BaseModel):
    Identifier: str
    Devices: List[Device2]
    MUXes: List[MUX]


class JTAGItem(BaseModel):
    Identifier: str
    Description: str
    Trees: List[Tree2]


class GPIO(BaseModel):
    Identifier: str
    Latency: str
    BitStart: int
    BitStop: int
    VirtualWireAlias: str
    Description: str


class Region1(BaseModel):
    Identifier: str
    SizeBytes: int
    Offset: int
    Description: str


class Data(BaseModel):
    Regions: List[Region1]


class Channels(BaseModel):
    GPIOs: List[GPIO]
    I2C: List[str]
    UART: List[str]
    Data: Data


class LTPIItem(BaseModel):
    Identifier: str
    RequiredPowerState: str
    MaxClockSpeedMHz: int
    Revision: str
    Version: str
    SilkscreenName: str
    ReferenceDesignator: str
    Description: str
    Channels: Channels


class Component(BaseModel):
    Identifier: str
    Type: str
    RootPort: int
    Width: str
    LaneMapping: List[int]
    DMASupported: bool
    HotPlugSupported: bool
    VendorID: str
    SubvendorID: str
    DeviceID: str
    SubdeviceID: str
    Manufacturer: List[str]
    ModelNumber: List[str]
    CxlSupported: bool
    CxlVersionMinimum: int
    SilkscreenName: str
    ReferenceDesignator: str
    PhysicalLocation: PhysicalLocation
    PciRootPort: int
    PCIeLinkSpeedSupportedMaximumMBPerSec: int
    PCIeLinkWidthSupportedMaximum: str
    BifurcationCapable: bool
    BifurcationMinimum: str
    Lanes: Optional[int] = None
    Endpoints: Optional[List[str]] = None
    Ports: Optional[int] = None
    Version: Optional[int] = None
    LatencyNS: Optional[int] = None


class Connector(BaseModel):
    Type: str
    Alias: str
    Mapping: str


class Fabric(BaseModel):
    Identifier: str
    Components: List[Component]
    Connectors: List[Connector]


class PCIeItem(BaseModel):
    Identifier: str
    Lanes: int
    Version: int
    Root: str
    Fabric: Fabric


class PECIItem(BaseModel):
    Identifier: str
    ConnectedDevices: List[ConnectedDevice]


class QSPIItem(BaseModel):
    Identifier: str
    MaxClockSpeedMHz: int
    AlertUsage: str
    SecondaryChipSelect: bool
    Density: str
    ConnectedDevices: List[ConnectedDevice]


class SGMIIItem(BaseModel):
    Identifier: str
    ConnectedDevices: List[ConnectedDevice]


class SPIItem(BaseModel):
    Identifier: str
    ControlPanelConnectorPresent: bool
    HpmFpgaConnected: bool
    MaxClockSpeedMHz: int
    SecondaryChipSelect: bool
    Density: str
    ConnectedDevices: List[ConnectedDevice]


class Mailbox(BaseModel):
    Version: int
    Supported: int


class VirtualWire1(BaseModel):
    Identifier: str
    Bit: int
    Mapping: str


class SGPIOItem(BaseModel):
    Identifier: str
    Type: str
    Version: str
    SilkscreenName: str
    ReferenceDesignator: str
    Mailbox: Mailbox
    VirtualWires: List[VirtualWire1]


class Device3(BaseModel):
    Identifier: str
    SpeedMaxBaud: int
    DataBits: int
    StopBits: int
    FlowControl: str
    PhysicalLocation: PhysicalLocation
    Description: str
    Manufacturers: List[str]
    Models: List[str]
    SilkscreenName: str
    ReferenceDesignator: str


class Channel2(BaseModel):
    Identifier: str
    Endpoint: str


class Mux1(BaseModel):
    Identifier: str
    PropagationDelayUS: int
    Channels: List[Channel2]
    PhysicalLocation: PhysicalLocation
    SilkscreenName: str
    ReferenceDesignator: str


class Tree3(BaseModel):
    Identifier: str
    Devices: List[Device3]
    Muxes: List[Mux1]


class UARTItem(BaseModel):
    Identifier: str
    VoltageTenthsVolts: int
    PowerState: str
    Trees: List[Tree3]


class Device4(BaseModel):
    Identifier: str
    Type: str
    Accessibility: str
    PhysicalPortType: str
    ProtocolVersionMaxSupported: str
    AuthenticationSupported: bool
    Manufacturers: List[str]
    Models: List[str]
    SilkscreenName: str
    ReferenceDesignator: str
    Description: str
    PhysicalLocation: PhysicalLocation


class Port1(BaseModel):
    Identifier: str
    VoltageTenthsVolts: int
    Endpoint: str


class Hub1(BaseModel):
    Identifier: str
    Ports: List[Port1]
    Manufacturers: List[str]
    Models: List[str]
    SilkscreenName: str
    ReferenceDesignator: str
    Description: str
    PhysicalLocation: PhysicalLocation


class Bridge1(BaseModel):
    Identifier: str
    Manufacturers: List[str]
    Models: List[str]
    Version: str
    LinkedBuses: List[str]


class Tree4(BaseModel):
    Identifier: str
    Devices: List[Device4]
    Hubs: List[Hub1]
    Bridges: List[Bridge1]


class USBItem(BaseModel):
    Identifier: str
    Type: str
    Reachability: str
    VoltageTenthsVolts: int
    PowerState: str
    ProtocolVersionMaxSupported: str
    Description: str
    Trees: List[Tree4]


class Buses(BaseModel):
    DisplayPort: List[DisplayPortItem]
    ESPI: List[ESPIItem]
    I2C: List[I2CItem]
    I3C: List[I3CItem]
    JTAG: List[JTAGItem]
    LTPI: List[LTPIItem]
    PCIe: List[PCIeItem]
    PECI: List[PECIItem]
    QSPI: List[QSPIItem]
    SGMII: List[SGMIIItem]
    SPI: List[SPIItem]
    SGPIO: List[SGPIOItem]
    UART: List[UARTItem]
    USB: List[USBItem]


class FRU(BaseModel):
    field_comment: str = Field(..., alias="_comment")
    Version: float
    HPM: HPM
    FPGA: FPGA
    Buses: Buses
