# generated by datamodel-codegen:
#   filename:  hardware-component-v0_5_6.json
#   timestamp: 2025-10-27T16:04:39+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr


class ComponentClass(Enum):
    hpm = "HPM"
    riser = "Riser"
    backplane = "Backplane"
    power_distribution_board = "PowerDistributionBoard"
    other = "Other"


class PowerPolicy(Enum):
    g3 = "G3"
    pre_stby = "Pre-STBY"
    stby = "STBY"
    s5 = "S5"
    s0 = "S0"


class MemoryTechnology(Enum):
    ddr4 = "DDR4"
    ddr5 = "DDR5"
    ddr6 = "DDR6"
    other = "Other"


class Proximity(Enum):
    near = "Near"
    far = "Far"


class FormFactor(Enum):
    sff = "SFF"
    tsff = "TSFF"
    other = "Other"


class Direction(Enum):
    upstream = "Upstream"
    downstream = "Downstream"


class CommonCircuitType(Enum):
    single_node = "Single Node"
    dual_node = "Dual Node"
    other = "Other"


class ConnectorType(Enum):
    a = "A"
    c = "C"
    other = "other"


class Destination(Enum):
    internal = "Internal"
    external = "External"


class AlertUsage(Enum):
    embedded = "Embedded"
    discrete = "Discrete"


class Density(Enum):
    quad = "Quad"
    dual = "Dual"
    single = "Single"


class IoType(Enum):
    push_pull = "push-pull"
    open_drain = "open drain"
    open_collector = "open collector"


class ProtocolType(Enum):
    basic = "Basic"
    standard = "Standard"


class TargetPortMode(Enum):
    basic = "Basic"
    standard = "Standard"


class Polarity(Enum):
    active_high = "active_high"
    active_low = "active_low"


class IsolationControlItem(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    signal: Optional[str] = Field(None, alias="Signal")
    """
    The signal that controls this isolation mechanism.
    """
    polarity: Optional[Polarity] = Field(None, alias="Polarity")
    """
    The polarity of the signal that controls this isolation mechanism.
    """


class Root(Enum):
    host = "Host"
    bmc = "BMC"
    other = "Other"


class Type(Enum):
    device = "Device"
    bridge = "Bridge"
    switch = "Switch"


class HostController(Enum):
    host = "Host"
    bmc = "BMC"


class NamedComponent(RootModel[str]):
    root: str
    """
    A component that is named so as to be referenceable.
    """


class ComponentAlias(RootModel[str]):
    root: str
    """
    A secondary reference name for a component.
    """


class AttachedConnectorListItem(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    type: Optional[str] = Field(None, alias="Type")
    """
    The type of connector for this reference.
    """
    chip_select: Optional[float] = Field(None, alias="ChipSelect")
    """
    The chip selection pin needed to access this device. This is primarily intended for use with ESPI, QSPI and SPI bus connections.
    """
    endpoint: Optional[str] = Field(None, alias="Endpoint")
    """
    The endpoint connector for this reference.
    """
    mmbi_capable: Optional[bool] = Field(None, alias="MMBICapable")
    """
    Whether the connector supports MMBI via the attached bus.
    """


class AttachedConnectorList(RootModel[List[AttachedConnectorListItem]]):
    root: List[AttachedConnectorListItem]
    """
    A collection of references to connectors attached to a bus.
    """


class ConnectedDeviceListItem(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    endpoint: Optional[str] = Field(None, alias="Endpoint")
    """
    This instance of a connected device.
    """
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    address: Optional[str] = Field(None, alias="Address")
    """
    The bus-specific hardware address needed to access a connected device, such as an I2C address.
    """
    random_access_capable: Optional[bool] = Field(None, alias="RandomAccessCapable")
    """
    Indicates whether the BMC can access memory on this device in random fashion through this connection.
    """
    chip_select: Optional[float] = Field(None, alias="ChipSelect")
    """
    The chip selection pin needed to access this device. This is primarily intended for use with ESPI, QSPI and SPI bus connections.
    """


class ConnectedDeviceList(RootModel[List[ConnectedDeviceListItem]]):
    root: List[ConnectedDeviceListItem]
    """
    Information about devices connected to a bus.
    """


class PhysicalLocation(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    upper_x_mils: Optional[int] = Field(None, alias="UpperXMils")
    """
    The upper x-axis corner of the bounding box surrounding the component, in millimeters.
    """
    upper_y_mils: Optional[int] = Field(None, alias="UpperYMils")
    """
    The upper y-axis corner of the bounding box surrounding the component, in millimeters.
    """
    lower_x_mils: Optional[int] = Field(None, alias="LowerXMils")
    """
    The lower x-axis corner of the bounding box surrounding the component, in millimeters.
    """
    lower_y_mils: Optional[int] = Field(None, alias="LowerYMils")
    """
    The lower y-axis corner of the bounding box surrounding the component, in millimeters.
    """


class SilkscreenName(RootModel[str]):
    root: str
    """
    The name silkscreened onto the HPM board for the component.
    """


class ReferenceDesignator(RootModel[str]):
    root: str
    """
    The reference designator used to logically describe the component in the BOM list.
    """


class RequiredPowerState(Enum):
    g3 = "G3"
    pre_stby = "Pre-STBY"
    stby = "STBY"
    s5 = "S5"
    s0 = "S0"
    other = "Other"


class Models(RootModel[List[str]]):
    root: List[str]
    """
    The possible models for this component.
    """


class Manufacturers(RootModel[List[str]]):
    root: List[str]
    """
    The possible manufacturers for this component.
    """


class Endpoint(RootModel[str]):
    root: str
    """
    An endpoint attached to this component.
    """


class MUXChannelConfigItem(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    mux_pin: Optional[str] = Field(None, alias="MUXPin")
    """
    A pin needed to select this MUX channel.
    """
    setting: Optional[float] = Field(None, alias="Setting")
    """
    The setting needed on a pin to select this MUX channel.
    """


class MUXChannelConfig(RootModel[List[MUXChannelConfigItem]]):
    root: List[MUXChannelConfigItem]
    """
    Information about selecting a channel in a MUX.
    """


class Signal1(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    type: Optional[str] = Field(None, alias="Type")
    """
    The type locating the signal used to control the pin.
    """
    type_id: Optional[str] = Field(None, alias="TypeID")
    """
    The specific device housing the signal used to control the pin.
    """
    subtype: Optional[str] = Field(None, alias="Subtype")
    """
    The subtype locating the signal used to control the pina pin.
    """
    subtype_id: Optional[str] = Field(None, alias="SubtypeID")
    """
    The specific signal used to control the pin.
    """


class MUXControlItem(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    mux_pin: Optional[str] = Field(None, alias="MUXPin")
    """
    A pin used to control this MUX channel.
    """
    signal: Optional[Signal1] = Field(None, alias="Signal")
    """
    The signal used to control the pin.
    """


class MUXControl(RootModel[List[MUXControlItem]]):
    root: List[MUXControlItem]
    """
    Information about mechanisms used to control this MUX.
    """


class Signal(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    connector_name: Optional[str] = Field(None, alias="ConnectorName")
    """
    The name of the signal as defined by a connector.
    """
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    type: Optional[str] = Field(None, alias="Type")
    """
    The type for this physical signal.
    """
    type_id: Optional[NamedComponent] = Field(None, alias="TypeID")
    subtype: Optional[str] = Field(None, alias="Subtype")
    """
    The connector subtype for this physical signal.
    """
    subtype_id: Optional[NamedComponent] = Field(None, alias="SubtypeID")
    physical_pin: Optional[str] = Field(None, alias="PhysicalPin")
    """
    The physical pin for this physical signal reference.
    """
    netlist_name: Optional[str] = Field(None, alias="NetlistName")
    """
    The Netlist name for this physical signal reference.
    """


class ConnectorsComposite(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    connector_type: Optional[str] = Field(None, alias="ConnectorType")
    """
    The type of the composite.
    """
    data_file: Optional[str] = Field(None, alias="DataFile")
    """
    The data file with JSON information specific to this composite.
    """
    silkscreen_name: Optional[SilkscreenName] = Field(None, alias="SilkscreenName")
    reference_designator: Optional[ReferenceDesignator] = Field(None, alias="ReferenceDesignator")
    mpi_cs: Optional[List[str]] = Field(None, alias="MPICs")
    """
    The MPICs used by the composite.
    """
    mxi_os: Optional[List[str]] = Field(None, alias="MXIOs")
    """
    The MXIOs used by the composite.
    """
    physical_location: Optional[PhysicalLocation] = Field(None, alias="PhysicalLocation")


class FlexIO(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    netlist_name: Optional[str] = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this FLEXIO.
    """


class Sideband(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    netlist_name: Optional[str] = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this sideband.
    """


class BusesDisplayPort(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    netlist_name: Optional[str] = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this bus.
    """
    connected_devices: Optional[ConnectedDeviceList] = Field(None, alias="ConnectedDevices")
    connectors: Optional[AttachedConnectorList] = Field(None, alias="Connectors")


class BusesESPI(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    netlist_name: Optional[str] = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this bus.
    """
    max_clock_speed_m_hz: Optional[int] = Field(None, alias="MaxClockSpeedMHz")
    """
    The maximum clock speed for this ESPI bus.
    """
    alert_usage: Optional[AlertUsage] = Field(None, alias="AlertUsage")
    """
    The manner in which alerts are signaled on the bus.
    """
    density: Optional[Density] = Field(None, alias="Density")
    """
    The data transfer mode supported by this ESPI bus.
    """
    controller: Optional[str] = Field(None, alias="Controller")
    """
    The component that receives interrupt requests and controls this bus.
    """
    connected_devices: Optional[ConnectedDeviceList] = Field(None, alias="ConnectedDevices")
    connectors: Optional[AttachedConnectorList] = Field(None, alias="Connectors")


class Channel(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    voltage_tenths_volts: Optional[int] = Field(None, alias="VoltageTenthsVolts")
    """
    The voltage needed to drive this MUX channel.
    """
    io_type: Optional[IoType] = Field(None, alias="IOType")
    """
    The type of I/O used for this MUX channel.
    """
    mux_config: Optional[MUXChannelConfig] = Field(None, alias="MUXConfig")
    endpoint: Optional[Endpoint] = Field(None, alias="Endpoint")


class MuX(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    channels: Optional[List[Channel]] = Field(None, alias="Channels")
    """
    Information about I2C MUXes in this I2C segment.
    """
    propagation_delay_ns: Optional[int] = Field(None, alias="PropagationDelayNS")
    """
    The propagation delay for this MUX.
    """
    address: Optional[str] = Field(None, alias="Address")
    """
    The I2C address for this MUX.
    """
    models: Optional[Models] = Field(None, alias="Models")
    manufacturers: Optional[Manufacturers] = Field(None, alias="Manufacturers")
    isolation_capable: Optional[bool] = Field(None, alias="IsolationCapable")
    """
    Indicates whether the MUX can isolate voltage for channels.
    """
    rise_time_ns: Optional[int] = Field(None, alias="RiseTimeNS")
    """
    The rise time for this MUX.
    """
    fall_time_ns: Optional[int] = Field(None, alias="FallTimeNS")
    """
    The fall time for this MUX.
    """
    control: Optional[MUXControl] = Field(None, alias="Control")
    silkscreen_name: Optional[SilkscreenName] = Field(None, alias="SilkscreenName")
    reference_designator: Optional[ReferenceDesignator] = Field(None, alias="ReferenceDesignator")
    description: Optional[str] = Field(None, alias="Description")
    """
    A description of the intended usage for this MUX.
    """
    physical_location: Optional[PhysicalLocation] = Field(None, alias="PhysicalLocation")


class Port(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    voltage_tenths_volts: Optional[int] = Field(None, alias="VoltageTenthsVolts")
    """
    The voltage needed to drive this I3C port.
    """
    target_port_mode: Optional[TargetPortMode] = Field(None, alias="TargetPortMode")
    """
    The target mode for this I3C port.
    """
    endpoint: Optional[Endpoint] = Field(None, alias="Endpoint")
    description: Optional[str] = Field(None, alias="Description")
    """
    A description of the intended usage for this port.
    """


class Hub(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    ports: Optional[List[Port]] = Field(None, alias="Ports")
    """
    Information about I3C ports.
    """
    propagation_delay_ns: Optional[int] = Field(None, alias="PropagationDelayNS")
    """
    The propagation delay for an I3C Hub.
    """
    address: Optional[str] = Field(None, alias="Address")
    """
    The I3C address at which this hub responds.
    """
    models: Optional[Models] = Field(None, alias="Models")
    manufacturers: Optional[Manufacturers] = Field(None, alias="Manufacturers")
    silkscreen_name: Optional[SilkscreenName] = Field(None, alias="SilkscreenName")
    reference_designator: Optional[ReferenceDesignator] = Field(None, alias="ReferenceDesignator")
    description: Optional[str] = Field(None, alias="Description")
    """
    A description of the intended usage for this hub.
    """


class Channel1(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    voltage_tenths_volts: Optional[int] = Field(None, alias="VoltageTenthsVolts")
    """
    The voltage needed to drive this MUX channel.
    """
    mux_config: Optional[MUXChannelConfig] = Field(None, alias="MUXConfig")
    endpoint: Optional[Endpoint] = Field(None, alias="Endpoint")


class MuX1(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    channels: Optional[List[Channel1]] = Field(None, alias="Channels")
    """
    Information about channels in this I3C MUX.
    """
    control: Optional[MUXControl] = Field(None, alias="Control")
    propagation_delay_ns: Optional[int] = Field(None, alias="PropagationDelayNS")
    """
    The propagation delay for this MUX.
    """
    address: Optional[str] = Field(None, alias="Address")
    """
    The I3C address for this MUX.
    """
    models: Optional[Models] = Field(None, alias="Models")
    manufacturers: Optional[Manufacturers] = Field(None, alias="Manufacturers")
    level_shifting_capable: Optional[bool] = Field(None, alias="LevelShiftingCapable")
    """
    Indicates whether the MUX can shift between voltage levels.
    """
    fault_detection_capable: Optional[bool] = Field(None, alias="FaultDetectionCapable")
    """
    Indicates whether the MUX can detect faults.
    """
    fault_clear_signal_capable: Optional[bool] = Field(None, alias="FaultClearSignalCapable")
    """
    Indicates whether the MUX can utilize a fault clear signal.
    """
    rise_time_ns: Optional[int] = Field(None, alias="RiseTimeNS")
    """
    The rise time for this MUX.
    """
    fall_time_ns: Optional[int] = Field(None, alias="FallTimeNS")
    """
    The fall time for this MUX.
    """
    silkscreen_name: Optional[SilkscreenName] = Field(None, alias="SilkscreenName")
    reference_designator: Optional[ReferenceDesignator] = Field(None, alias="ReferenceDesignator")
    description: Optional[str] = Field(None, alias="Description")
    """
    A description of the intended usage for this MUX.
    """
    physical_location: Optional[PhysicalLocation] = Field(None, alias="PhysicalLocation")


class Segment1(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    netlist_name: Optional[str] = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this segment.
    """
    hubs: Optional[List[Hub]] = Field(None, alias="Hubs")
    """
    Information about I3C hubs.
    """
    mu_xes: Optional[List[MuX1]] = Field(None, alias="MUXes")
    """
    Information about I3C MUXes.
    """
    connected_devices: Optional[ConnectedDeviceList] = Field(None, alias="ConnectedDevices")
    connectors: Optional[AttachedConnectorList] = Field(None, alias="Connectors")


class BusesI3C(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    netlist_name: Optional[str] = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this bus.
    """
    protocol_type: Optional[ProtocolType] = Field(None, alias="ProtocolType")
    """
    The protocol type for this I3C bus.
    """
    voltage_tenths_volts: Optional[int] = Field(None, alias="VoltageTenthsVolts")
    """
    The voltage needed to drive this I3C bus.
    """
    required_power_state: Optional[RequiredPowerState] = Field(None, alias="RequiredPowerState")
    frequency_k_hz: Optional[int] = Field(None, alias="FrequencyKHz")
    """
    The frequency at which this I3C bus shall operate.
    """
    segments: Optional[List[Segment1]] = Field(None, alias="Segments")
    """
    Information about I3C segments.
    """


class Channel2(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    endpoint: Optional[Endpoint] = Field(None, alias="Endpoint")
    mux_config: Optional[MUXChannelConfig] = Field(None, alias="MUXConfig")
    description: Optional[str] = Field(None, alias="Description")
    """
    A description for this JTAG MUX channel.
    """


class MuX2(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    channels: Optional[List[Channel2]] = Field(None, alias="Channels")
    """
    Information about channels in a JTAG MUX.
    """


class Segment2(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    mu_xes: Optional[List[MuX2]] = Field(None, alias="MUXes")
    """
    Information about MUXes in a JTAG segment.
    """
    control: Optional[MUXControl] = Field(None, alias="Control")
    connected_devices: Optional[ConnectedDeviceList] = Field(None, alias="ConnectedDevices")
    connectors: Optional[AttachedConnectorList] = Field(None, alias="Connectors")


class BusesJTAG(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    netlist_name: Optional[str] = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this bus.
    """
    segments: Optional[List[Segment2]] = Field(None, alias="Segments")
    """
    Information about JTAG segments.
    """


class BusesLTPI(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    netlist_name: Optional[str] = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this bus.
    """
    required_power_state: Optional[RequiredPowerState] = Field(None, alias="RequiredPowerState")
    max_clock_speed_m_hz: Optional[int] = Field(None, alias="MaxClockSpeedMHz")
    """
    The maximum clock speed for this LTPI bus.
    """
    connected_devices: Optional[ConnectedDeviceList] = Field(None, alias="ConnectedDevices")
    connectors: Optional[AttachedConnectorList] = Field(None, alias="Connectors")


class BusesMPESTI(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    netlist_name: Optional[str] = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this bus.
    """
    connected_devices: Optional[ConnectedDeviceList] = Field(None, alias="ConnectedDevices")
    connectors: Optional[AttachedConnectorList] = Field(None, alias="Connectors")


class Channel3(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    endpoint: Optional[str] = Field(None, alias="Endpoint")
    """
    The endpoint to which this channel is connnected.
    """


class Isolation(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    channels: Optional[List[Channel3]] = Field(None, alias="Channels")
    """
    Information about channels for isolation management.
    """
    isolation_control: Optional[List[IsolationControlItem]] = Field(None, alias="IsolationControl")
    """
    Information about control for isolation management.
    """


class Segment3(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    netlist_name: Optional[str] = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this segment.
    """
    isolation: Optional[Isolation] = Field(None, alias="Isolation")
    """
    Information about isolation management for this NC-SI RBT bus.
    """
    connected_devices: Optional[ConnectedDeviceList] = Field(None, alias="ConnectedDevices")
    connectors: Optional[AttachedConnectorList] = Field(None, alias="Connectors")


class BusesNCSIRBT(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    netlist_name: Optional[str] = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this bus.
    """
    segments: Optional[List[Segment3]] = Field(None, alias="Segments")
    """
    Information about segments for this NC-SI RBT bus.
    """


class Component1(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    type: Optional[Type] = Field(None, alias="Type")
    """
    The type of this PCIe component.
    """
    version: Optional[int] = Field(None, alias="Version")
    """
    The highest version of the PCIe specification supported by this PCIe component.
    """
    vendor_id: Optional[str] = Field(None, alias="VendorID")
    """
    The PCIe vendor ID for this PCIe component.
    """
    subvendor_id: Optional[str] = Field(None, alias="SubvendorID")
    """
    The PCIe subvendor ID for this PCIe component.
    """
    device_id: Optional[str] = Field(None, alias="DeviceID")
    """
    The PCIe device ID for this PCIe component.
    """
    subdevice_id: Optional[str] = Field(None, alias="SubdeviceID")
    """
    The PCIe subdevice ID for this PCIe component.
    """
    root_port: Optional[str] = Field(None, alias="RootPort")
    """
    The root port associated with this PCIe component.
    """
    width: Optional[str] = Field(None, alias="Width")
    """
    The width, in PCIe lanes, for this PCIe component.
    """
    lane_mapping: Optional[List[int]] = Field(None, alias="LaneMapping")
    """
    The mapping of lanes for this PCIe component.
    """
    hot_plug_supported: Optional[bool] = Field(None, alias="HotPlugSupported")
    """
    Indicates whether the PCIe component is hot-pluggable.
    """
    dma_supported: Optional[bool] = Field(None, alias="DMASupported")
    """
    Indicates whether the PCIe component supports direct memory access.
    """
    cxl_supported: Optional[bool] = Field(None, alias="CxlSupported")
    """
    Indicates whether the PCIe component supports Compute Express Link (CXL).
    """
    cxl_version_minimum: Optional[str] = Field(None, alias="CxlVersionMinimum")
    """
    The maximum version of the CXL specification supported by this PCIe component.
    """
    link_speed_supported_maximum_gb_per_sec: Optional[int] = Field(None, alias="LinkSpeedSupportedMaximumGBPerSec")
    """
    The maximum link speed supported by this PCIe component.
    """
    bifurcation_capable: Optional[bool] = Field(None, alias="BifurcationCapable")
    """
    Indicates whether the PCIe component supports bifurcation of its PCIe lanes.
    """
    bifurcation_minimum: Optional[int] = Field(None, alias="BifurcationMinimum")
    """
    The minimum lane width supported by this PCIe component for bifurcation.
    """
    ports: Optional[int] = Field(None, alias="Ports")
    """
    The number of PCIe ports supported by this PCIe switch.
    """
    latency_ns: Optional[int] = Field(None, alias="LatencyNS")
    """
    The latency of this PCIe switch.
    """
    models: Optional[Models] = Field(None, alias="Models")
    manufacturers: Optional[Manufacturers] = Field(None, alias="Manufacturers")
    silkscreen_name: Optional[SilkscreenName] = Field(None, alias="SilkscreenName")
    reference_designator: Optional[ReferenceDesignator] = Field(None, alias="ReferenceDesignator")
    physical_location: Optional[PhysicalLocation] = Field(None, alias="PhysicalLocation")
    endpoint: Optional[Endpoint] = Field(None, alias="Endpoint")


class Fabric(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    netlist_name: Optional[str] = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this fabric.
    """
    host_soc_root_port: Optional[str] = Field(None, alias="HostSOCRootPort")
    """
    The assigned port for the SOC PCIe root complex enumeration.
    """
    first_lane: Optional[int] = Field(None, alias="FirstLane")
    """
    The first PCIe lane used for this fabric.
    """
    width: Optional[int] = Field(None, alias="Width")
    """
    The number of PCIe lanes used for this fabric.
    """
    components: Optional[List[Component1]] = Field(None, alias="Components")
    """
    Information about PCIe components in a PCIe bus.
    """
    connected_devices: Optional[ConnectedDeviceList] = Field(None, alias="ConnectedDevices")
    connectors: Optional[AttachedConnectorList] = Field(None, alias="Connectors")


class BusesPCIe(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    netlist_name: Optional[str] = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this bus.
    """
    lanes: Optional[int] = Field(None, alias="Lanes")
    """
    The number of PCIe lanes for this bus.
    """
    version: Optional[float] = Field(None, alias="Version")
    """
    The highest generation version of PCIe supported by this bus.
    """
    root: Optional[Root] = Field(None, alias="Root")
    """
    The location of the PCIe root.
    """
    fabric: Optional[Fabric] = Field(None, alias="Fabric")
    """
    Information about PCIe bus fabrics.
    """


class BusesPECI(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    netlist_name: Optional[str] = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this bus.
    """
    connected_devices: Optional[ConnectedDeviceList] = Field(None, alias="ConnectedDevices")
    connectors: Optional[AttachedConnectorList] = Field(None, alias="Connectors")


class BusesQSPI(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    netlist_name: Optional[str] = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this bus.
    """
    max_clock_speed_m_hz: Optional[int] = Field(None, alias="MaxClockSpeedMHz")
    """
    The maximum clock speed for this QSPI bus.
    """
    density: Optional[Density] = Field(None, alias="Density")
    """
    The data transfer mode supported by this ESPI bus.
    """
    controller: Optional[str] = Field(None, alias="Controller")
    """
    The component that receives interrupt requests and controls this bus.
    """
    connected_devices: Optional[ConnectedDeviceList] = Field(None, alias="ConnectedDevices")
    connectors: Optional[AttachedConnectorList] = Field(None, alias="Connectors")


class BusesSGMII(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    netlist_name: Optional[str] = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this bus.
    """
    connected_devices: Optional[ConnectedDeviceList] = Field(None, alias="ConnectedDevices")
    connectors: Optional[AttachedConnectorList] = Field(None, alias="Connectors")


class BusesSPI(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    netlist_name: Optional[str] = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this bus.
    """
    max_clock_speed_m_hz: Optional[int] = Field(None, alias="MaxClockSpeedMHz")
    """
    The maximum clock speed for this SPI bus.
    """
    alert_usage: Optional[AlertUsage] = Field(None, alias="AlertUsage")
    """
    The manner in which alerts are signaled on the bus.
    """
    density: Optional[Density] = Field(None, alias="Density")
    """
    The data transfer mode supported by this ESPI bus.
    """
    interrupt_request: Optional[str] = Field(None, alias="InterruptRequest")
    """
    Indicates the component to which the IRQ[0] pin is connected.
    """
    controller: Optional[str] = Field(None, alias="Controller")
    """
    The component that receives interrupt requests and controls this bus.
    """
    connected_devices: Optional[ConnectedDeviceList] = Field(None, alias="ConnectedDevices")
    connectors: Optional[AttachedConnectorList] = Field(None, alias="Connectors")


class BusesSGPIO(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    netlist_name: Optional[str] = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this bus.
    """
    connected_devices: Optional[ConnectedDeviceList] = Field(None, alias="ConnectedDevices")
    connectors: Optional[AttachedConnectorList] = Field(None, alias="Connectors")


class Channel4(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    endpoint: Optional[Endpoint] = Field(None, alias="Endpoint")
    mux_config: Optional[MUXChannelConfig] = Field(None, alias="MUXConfig")


class MuX3(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    propagation_delay_ns: Optional[int] = Field(None, alias="PropagationDelayNS")
    """
    The propagation delay for this UART MUX.
    """
    channels: Optional[List[Channel4]] = Field(None, alias="Channels")
    """
    Information about channels in a UART MUX.
    """
    control: Optional[MUXControl] = Field(None, alias="Control")
    silkscreen_name: Optional[SilkscreenName] = Field(None, alias="SilkscreenName")
    reference_designator: Optional[ReferenceDesignator] = Field(None, alias="ReferenceDesignator")
    physical_location: Optional[PhysicalLocation] = Field(None, alias="PhysicalLocation")


class Segment4(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    mu_xes: Optional[List[MuX3]] = Field(None, alias="MUXes")
    """
    Information about MUXes in a UART segment.
    """
    connected_devices: Optional[ConnectedDeviceList] = Field(None, alias="ConnectedDevices")
    connectors: Optional[AttachedConnectorList] = Field(None, alias="Connectors")


class BusesUART(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    netlist_name: Optional[str] = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this bus.
    """
    voltage_tenths_volts: Optional[int] = Field(None, alias="VoltageTenthsVolts")
    """
    The voltage needed to drive this UART bus.
    """
    required_power_state: Optional[RequiredPowerState] = Field(None, alias="RequiredPowerState")
    segments: Optional[List[Segment4]] = Field(None, alias="Segments")
    """
    Information about UART segments.
    """


class MuX4(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    propagation_delay_ns: Optional[int] = Field(None, alias="PropagationDelayNS")
    """
    The propagation delay for this MUX.
    """
    channels: Optional[List[Channel4]] = Field(None, alias="Channels")
    """
    Information about channels in this MUX.
    """
    control: Optional[MUXControl] = Field(None, alias="Control")
    silkscreen_name: Optional[SilkscreenName] = Field(None, alias="SilkscreenName")
    reference_designator: Optional[ReferenceDesignator] = Field(None, alias="ReferenceDesignator")
    physical_location: Optional[PhysicalLocation] = Field(None, alias="PhysicalLocation")


class Port1(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    voltage_tenths_volts: Optional[int] = Field(None, alias="VoltageTenthsVolts")
    """
    The voltage needed to drive this USB port.
    """
    endpoint: Optional[Endpoint] = Field(None, alias="Endpoint")


class Hub1(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    ports: Optional[List[Port1]] = Field(None, alias="Ports")
    """
    Information about ports for this USB bus hub.
    """
    models: Optional[Models] = Field(None, alias="Models")
    manufacturers: Optional[Manufacturers] = Field(None, alias="Manufacturers")
    silkscreen_name: Optional[SilkscreenName] = Field(None, alias="SilkscreenName")
    reference_designator: Optional[ReferenceDesignator] = Field(None, alias="ReferenceDesignator")
    description: Optional[str] = Field(None, alias="Description")
    """
    A description of the intended usage for this hub.
    """
    physical_location: Optional[PhysicalLocation] = Field(None, alias="PhysicalLocation")


class ReferencedBusListItem(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    type: Optional[str] = Field(None, alias="Type")
    """
    The type of bus for this reference.
    """
    identifier: Optional[str] = Field(None, alias="Identifier")
    """
    The instance of the bus type for this reference.
    """
    spec_bus_name: Optional[str] = Field(None, alias="SpecBusName")
    """
    The name used in the spec to reference this bus.
    """
    signals: Optional[List[Signal]] = Field(None, alias="Signals")
    """
    Information about the signals for this referenced bus.
    """


class ReferencedBusList(RootModel[List[ReferencedBusListItem]]):
    root: List[ReferencedBusListItem]
    """
    A collection of references to hardware or logical buses as defined in the buses section of this document.
    """


class ConnectorsSOCs(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    vendor_name: Optional[str] = Field(None, alias="VendorName")
    """
    The name of the vendor of the SOC.
    """
    vendor_id: Optional[str] = Field(None, alias="VendorID")
    """
    The PCIe VendorID for the vendor of the SOC.
    """
    connector_type: Optional[str] = Field(None, alias="ConnectorType")
    """
    The type of the SOC.
    """
    silkscreen_name: Optional[SilkscreenName] = Field(None, alias="SilkscreenName")
    reference_designator: Optional[ReferenceDesignator] = Field(None, alias="ReferenceDesignator")
    dimm_channels_supported: Optional[int] = Field(None, alias="DimmChannelsSupported")
    """
    The number of dimm channels supported by the SOC.
    """
    physical_location: Optional[PhysicalLocation] = Field(None, alias="PhysicalLocation")
    models: Optional[Models] = Field(None, alias="Models")
    manufacturers: Optional[Manufacturers] = Field(None, alias="Manufacturers")
    connected_buses: Optional[ReferencedBusList] = Field(None, alias="ConnectedBuses")


class Slot(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    proximity: Optional[Proximity] = Field(None, alias="Proximity")
    """
    The proximity of the memory subsystem slot to its associated SOC.
    """
    silkscreen_name: Optional[SilkscreenName] = Field(None, alias="SilkscreenName")
    reference_designator: Optional[ReferenceDesignator] = Field(None, alias="ReferenceDesignator")
    associated_soc: Optional[str] = Field(None, alias="AssociatedSOC")
    """
    The SOC associated with this memory subsystem slot.
    """
    physical_location: Optional[PhysicalLocation] = Field(None, alias="PhysicalLocation")
    connected_buses: Optional[ReferencedBusList] = Field(None, alias="ConnectedBuses")


class ConnectorsMemorySubsystem(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    channel_count: Optional[int] = Field(None, alias="ChannelCount")
    """
    The number of channels supported by the memory subsystem.
    """
    slots_per_channel: Optional[Union[int, List[int]]] = Field(None, alias="SlotsPerChannel")
    """
    The number of slots in each channel supported by the memory subsystem.
    """
    memory_technology: Optional[MemoryTechnology] = Field(None, alias="MemoryTechnology")
    """
    The memory technology supported by the memory subsystem.
    """
    slots: Optional[List[Slot]] = Field(None, alias="Slots")
    """
    Information about an individual channels slot in the memory subsystem.
    """


class ConnectorsCoolingSubsystem(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    silkscreen_name: Optional[SilkscreenName] = Field(None, alias="SilkscreenName")
    reference_designator: Optional[ReferenceDesignator] = Field(None, alias="ReferenceDesignator")
    maximum_power_watts: Optional[int] = Field(None, alias="MaximumPowerWatts")
    """
    The maximum power for this cooling subsystem.
    """
    connected_buses: Optional[ReferencedBusList] = Field(None, alias="ConnectedBuses")
    models: Optional[Models] = Field(None, alias="Models")
    manufacturers: Optional[Manufacturers] = Field(None, alias="Manufacturers")
    physical_location: Optional[PhysicalLocation] = Field(None, alias="PhysicalLocation")


class ConnectorsDrive(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    silkscreen_name: Optional[SilkscreenName] = Field(None, alias="SilkscreenName")
    reference_designator: Optional[ReferenceDesignator] = Field(None, alias="ReferenceDesignator")
    drive_type: Optional[str] = Field(None, alias="DriveType")
    """
    The specific connector type for this drive, such as EDSFF or M.2.
    """
    connected_buses: Optional[ReferencedBusList] = Field(None, alias="ConnectedBuses")
    models: Optional[Models] = Field(None, alias="Models")
    manufacturers: Optional[Manufacturers] = Field(None, alias="Manufacturers")
    physical_location: Optional[PhysicalLocation] = Field(None, alias="PhysicalLocation")


class ConnectorsMxio(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    soc_socket_association: Optional[str] = Field(None, alias="SOCSocketAssociation")
    """
    The SOC Socket to which this MXIO is connected.
    """
    common_clocking_support: Optional[bool] = Field(None, alias="CommonClockingSupport")
    """
    Indicates whether the MXIO supports common clocking.
    """
    connector_type: Optional[str] = Field(None, alias="ConnectorType")
    """
    The type of connector for this MXIO.
    """
    connected_buses: Optional[ReferencedBusList] = Field(None, alias="ConnectedBuses")
    silkscreen_name: Optional[SilkscreenName] = Field(None, alias="SilkscreenName")
    reference_designator: Optional[ReferenceDesignator] = Field(None, alias="ReferenceDesignator")
    flex_i_os: Optional[List[FlexIO]] = Field(None, alias="FlexIOs")
    """
    The FlexIOs used by the MXIO.
    """
    signals: Optional[List[Signal]] = Field(None, alias="Signals")
    """
    Information about the signals for this MXIO.
    """
    physical_location: Optional[PhysicalLocation] = Field(None, alias="PhysicalLocation")


class ConnectorsMpic(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    connector_type: Optional[str] = Field(None, alias="ConnectorType")
    """
    The type of connector for this MPIC.
    """
    adjusted_maximum_actual_power_supported_watts: Optional[int] = Field(
        None, alias="AdjustedMaximumActualPowerSupportedWatts"
    )
    """
    The adjusted maximum actual power supported for this MPIC.
    """
    silkscreen_name: Optional[SilkscreenName] = Field(None, alias="SilkscreenName")
    reference_designator: Optional[ReferenceDesignator] = Field(None, alias="ReferenceDesignator")
    sidebands: Optional[List[Sideband]] = Field(None, alias="Sidebands")
    """
    The sidebands used by the MPIC.
    """
    connected_buses: Optional[ReferencedBusList] = Field(None, alias="ConnectedBuses")
    physical_location: Optional[PhysicalLocation] = Field(None, alias="PhysicalLocation")


class ConnectorsPowerSupply(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    connector_type: Optional[str] = Field(None, alias="ConnectorType")
    """
    The type of connector for this power supply.
    """
    silkscreen_name: Optional[SilkscreenName] = Field(None, alias="SilkscreenName")
    reference_designator: Optional[ReferenceDesignator] = Field(None, alias="ReferenceDesignator")
    hot_plug_supported: Optional[bool] = Field(None, alias="HotPlugSupported")
    """
    Indicates whether the power supply supports hot plugging.
    """
    connected_buses: Optional[ReferencedBusList] = Field(None, alias="ConnectedBuses")
    models: Optional[Models] = Field(None, alias="Models")
    manufacturers: Optional[Manufacturers] = Field(None, alias="Manufacturers")
    physical_location: Optional[PhysicalLocation] = Field(None, alias="PhysicalLocation")


class ConnectorsOCPMezzanineSlot(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    version: Optional[str] = Field(None, alias="Version")
    """
    The version of the OCP NIC specification with which this OCP mezzanine expansion slot complies.
    """
    silkscreen_name: Optional[SilkscreenName] = Field(None, alias="SilkscreenName")
    reference_designator: Optional[ReferenceDesignator] = Field(None, alias="ReferenceDesignator")
    form_factor: Optional[FormFactor] = Field(None, alias="FormFactor")
    """
    The form factor for this OCP mezzanine expansion slot.
    """
    connected_buses: Optional[ReferencedBusList] = Field(None, alias="ConnectedBuses")
    paired_slot_for_double_wide: Optional[str] = Field(None, alias="PairedSlotForDoubleWide")
    """
    The slot with which this slot is paired for use as a double-wide connector in the DSFF or TDSFF form factor.
    """
    signals: Optional[List[Signal]] = Field(None, alias="Signals")
    """
    Information about the signals for this OCP Mezzanine slot.
    """
    physical_location: Optional[PhysicalLocation] = Field(None, alias="PhysicalLocation")


class ConnectorsControlPanel(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    silkscreen_name: Optional[SilkscreenName] = Field(None, alias="SilkscreenName")
    reference_designator: Optional[ReferenceDesignator] = Field(None, alias="ReferenceDesignator")
    primary: Optional[bool] = Field(None, alias="Primary")
    """
    Indicates whether this is the primary control panel.
    """
    connected_buses: Optional[ReferencedBusList] = Field(None, alias="ConnectedBuses")
    models: Optional[Models] = Field(None, alias="Models")
    manufacturers: Optional[Manufacturers] = Field(None, alias="Manufacturers")
    physical_location: Optional[PhysicalLocation] = Field(None, alias="PhysicalLocation")


class ConnectorsPCIeCEM(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    connector_type: Optional[str] = Field(None, alias="ConnectorType")
    """
    The type for this CEM slot.
    """
    silkscreen_name: Optional[SilkscreenName] = Field(None, alias="SilkscreenName")
    reference_designator: Optional[ReferenceDesignator] = Field(None, alias="ReferenceDesignator")
    connected_buses: Optional[ReferencedBusList] = Field(None, alias="ConnectedBuses")
    signals: Optional[List[Signal]] = Field(None, alias="Signals")
    """
    Information about the signals for this PCIe CEM slot.
    """
    physical_location: Optional[PhysicalLocation] = Field(None, alias="PhysicalLocation")


class ConnectorsPowerDistributionBoardManagement(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    management_type: Optional[str] = Field(None, alias="ManagementType")
    """
    The type of power distribution management board connector, such as type 1 or type 2.
    """
    connector_type: Optional[str] = Field(None, alias="ConnectorType")
    """
    The connector type for this power distribution management board connector.
    """
    direction: Optional[Direction] = Field(None, alias="Direction")
    """
    The intended linkage for this power distribution management board connector.
    """
    sidebands: Optional[List[Sideband]] = Field(None, alias="Sidebands")
    """
    The sidebands used by the PDB.
    """
    silkscreen_name: Optional[SilkscreenName] = Field(None, alias="SilkscreenName")
    reference_designator: Optional[ReferenceDesignator] = Field(None, alias="ReferenceDesignator")
    connected_buses: Optional[ReferencedBusList] = Field(None, alias="ConnectedBuses")
    models: Optional[Models] = Field(None, alias="Models")
    manufacturers: Optional[Manufacturers] = Field(None, alias="Manufacturers")
    physical_location: Optional[PhysicalLocation] = Field(None, alias="PhysicalLocation")


class ConnectorsRealTimeClockBattery(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    silkscreen_name: Optional[SilkscreenName] = Field(None, alias="SilkscreenName")
    reference_designator: Optional[ReferenceDesignator] = Field(None, alias="ReferenceDesignator")
    physical_location: Optional[PhysicalLocation] = Field(None, alias="PhysicalLocation")
    connected_buses: Optional[ReferencedBusList] = Field(None, alias="ConnectedBuses")


class ConnectorsFan(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    pins: Optional[int] = Field(None, alias="Pins")
    """
    The number of pins for the connector for this fan.
    """
    maximum_power_watts: Optional[int] = Field(None, alias="MaximumPowerWatts")
    """
    The maximum power for this fan.
    """
    connector_type: Optional[str] = Field(None, alias="ConnectorType")
    """
    The type of connector for this fan.
    """
    silkscreen_name: Optional[SilkscreenName] = Field(None, alias="SilkscreenName")
    reference_designator: Optional[ReferenceDesignator] = Field(None, alias="ReferenceDesignator")
    hot_plug_supported: Optional[bool] = Field(None, alias="HotPlugSupported")
    """
    Indicates whether this fan supports hot plugging.
    """
    connected_buses: Optional[ReferencedBusList] = Field(None, alias="ConnectedBuses")
    models: Optional[Models] = Field(None, alias="Models")
    manufacturers: Optional[Manufacturers] = Field(None, alias="Manufacturers")
    physical_location: Optional[PhysicalLocation] = Field(None, alias="PhysicalLocation")


class ConnectorsSCI(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    revision: Optional[str] = Field(None, alias="Revision")
    """
    The revision of this SCI.
    """
    version: Optional[str] = Field(None, alias="Version")
    """
    The version of this SCI.
    """
    common_circuit_type: Optional[CommonCircuitType] = Field(None, alias="CommonCircuitType")
    """
    The number of nodes supported by this SCI.
    """
    backup_battery_voltage_measurement_capable: Optional[bool] = Field(
        None, alias="BackupBatteryVoltageMeasurementCapable"
    )
    """
    Indicates whether this SCI supports measurement of the backup battery voltage.
    """
    connected_buses: Optional[ReferencedBusList] = Field(None, alias="ConnectedBuses")
    silkscreen_name: Optional[SilkscreenName] = Field(None, alias="SilkscreenName")
    reference_designator: Optional[ReferenceDesignator] = Field(None, alias="ReferenceDesignator")
    models: Optional[Models] = Field(None, alias="Models")
    manufacturers: Optional[Manufacturers] = Field(None, alias="Manufacturers")
    signals: Optional[List[Signal]] = Field(None, alias="Signals")
    """
    Information about the signals for this SCI.
    """
    physical_location: Optional[PhysicalLocation] = Field(None, alias="PhysicalLocation")


class ConnectorsIntrusionDetection(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    silkscreen_name: Optional[SilkscreenName] = Field(None, alias="SilkscreenName")
    reference_designator: Optional[ReferenceDesignator] = Field(None, alias="ReferenceDesignator")
    connector_type: Optional[str] = Field(None, alias="ConnectorType")
    """
    The type of connector for this intrusion detection module.
    """
    status_signal_netname: Optional[str] = Field(None, alias="StatusSignalNetname")
    """
    The netname of the signal that provides the state of the intrusion detection sensor.
    """
    models: Optional[Models] = Field(None, alias="Models")
    manufacturers: Optional[Manufacturers] = Field(None, alias="Manufacturers")
    physical_location: Optional[PhysicalLocation] = Field(None, alias="PhysicalLocation")
    connected_buses: Optional[ReferencedBusList] = Field(None, alias="ConnectedBuses")


class ConnectorsPhysicalUSB(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    silkscreen_name: Optional[SilkscreenName] = Field(None, alias="SilkscreenName")
    reference_designator: Optional[ReferenceDesignator] = Field(None, alias="ReferenceDesignator")
    connector_type: Optional[ConnectorType] = Field(None, alias="ConnectorType")
    """
    The USB type of the connector for this physical USB port.
    """
    destination: Optional[Destination] = Field(None, alias="Destination")
    """
    The endpoint location of this physical USB port.
    """
    connected_buses: Optional[ReferencedBusList] = Field(None, alias="ConnectedBuses")
    models: Optional[Models] = Field(None, alias="Models")
    manufacturers: Optional[Manufacturers] = Field(None, alias="Manufacturers")
    physical_location: Optional[PhysicalLocation] = Field(None, alias="PhysicalLocation")


class ConnectorsOEM(BaseModel):
    model_config = ConfigDict(extra="allow", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    silkscreen_name: Optional[SilkscreenName] = Field(None, alias="SilkscreenName")
    reference_designator: Optional[ReferenceDesignator] = Field(None, alias="ReferenceDesignator")
    connector_type: Optional[str] = Field(None, alias="ConnectorType")
    """
    The type of this OEM connector.
    """
    connected_buses: Optional[ReferencedBusList] = Field(None, alias="ConnectedBuses")
    models: Optional[Models] = Field(None, alias="Models")
    manufacturers: Optional[Manufacturers] = Field(None, alias="Manufacturers")
    physical_location: Optional[PhysicalLocation] = Field(None, alias="PhysicalLocation")


class Device(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    type: Optional[str] = Field(None, alias="Type")
    """
    The type of the device.
    """
    models: Optional[Models] = Field(None, alias="Models")
    manufacturers: Optional[Manufacturers] = Field(None, alias="Manufacturers")
    active: Optional[bool] = Field(None, alias="Active")
    """
    Indicates whether this is an active programmable device.
    """
    primary: Optional[bool] = Field(None, alias="Primary")
    """
    Indicates whether this is the primary active programmable device.
    """
    data_file: Optional[str] = Field(None, alias="DataFile")
    """
    The data file with JSON information specific to this device.
    """
    silkscreen_name: Optional[SilkscreenName] = Field(None, alias="SilkscreenName")
    reference_designator: Optional[ReferenceDesignator] = Field(None, alias="ReferenceDesignator")
    capacity_bytes: Optional[float] = Field(None, alias="CapacityBytes")
    """
    The storage capacity for this device.
    """
    physical_signals: Optional[List[Signal]] = Field(None, alias="PhysicalSignals")
    """
    Information about the physical signals for this device.
    """
    connected_buses: Optional[ReferencedBusList] = Field(None, alias="ConnectedBuses")
    oem: Optional[Dict[str, Any]] = Field(None, alias="OEM")
    """
    Provides additional OEM-specific information for a device.
    """


class Devices(RootModel[List[Device]]):
    root: List[Device]
    """
    Information about active and passive hardware devices
    """


class Bridge(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    models: Optional[Models] = Field(None, alias="Models")
    manufacturers: Optional[Manufacturers] = Field(None, alias="Manufacturers")
    version: Optional[str] = Field(None, alias="Version")
    """
    The version for this bridge.
    """
    silkscreen_name: Optional[SilkscreenName] = Field(None, alias="SilkscreenName")
    reference_designator: Optional[ReferenceDesignator] = Field(None, alias="ReferenceDesignator")
    linked_buses: Optional[ReferencedBusList] = Field(None, alias="LinkedBuses")


class Segment(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    netlist_name: Optional[str] = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this segment.
    """
    connected_devices: Optional[ConnectedDeviceList] = Field(None, alias="ConnectedDevices")
    connectors: Optional[AttachedConnectorList] = Field(None, alias="Connectors")
    mu_xes: Optional[List[MuX]] = Field(None, alias="MUXes")
    """
    Information about I2C MUXes in this I2C segment.
    """
    bridges: Optional[List[Bridge]] = Field(None, alias="Bridges")
    """
    Information about I2C bridges in this I2C segment.
    """


class BusesI2C(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    netlist_name: Optional[str] = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this bus.
    """
    voltage_tenths_volts: Optional[int] = Field(None, alias="VoltageTenthsVolts")
    """
    The voltage needed to drive this bus.
    """
    required_power_state: Optional[RequiredPowerState] = Field(None, alias="RequiredPowerState")
    frequency_k_hz: Optional[int] = Field(None, alias="FrequencyKHz")
    """
    The clock frequency for this bus.
    """
    description: Optional[str] = Field(None, alias="Description")
    """
    A description of the intended usage for this bus.
    """
    segments: Optional[List[Segment]] = Field(None, alias="Segments")
    """
    Information about I2C segments.
    """


class Bridge1(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    models: Optional[Models] = Field(None, alias="Models")
    manufacturers: Optional[Manufacturers] = Field(None, alias="Manufacturers")
    version: Optional[str] = Field(None, alias="Version")
    """
    The version of USB supported by this USB bridge.
    """
    linked_buses: Optional[ReferencedBusList] = Field(None, alias="LinkedBuses")


class Segment5(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    connected_devices: Optional[ConnectedDeviceList] = Field(None, alias="ConnectedDevices")
    connectors: Optional[AttachedConnectorList] = Field(None, alias="Connectors")
    mu_xes: Optional[List[MuX4]] = Field(None, alias="MUXes")
    """
    Information about muxes for this USB bus.
    """
    hubs: Optional[List[Hub1]] = Field(None, alias="Hubs")
    """
    Information about hubs for this USB bus segment.
    """
    bridges: Optional[List[Bridge1]] = Field(None, alias="Bridges")
    """
    Information about bridges for this USB bus segment.
    """


class BusesUSB(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: Optional[NamedComponent] = Field(None, alias="Identifier")
    alias: Optional[ComponentAlias] = Field(None, alias="Alias")
    netlist_name: Optional[str] = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this bus.
    """
    supported_version: Optional[str] = Field(None, alias="SupportedVersion")
    """
    The maximum supported USB version for this USB bus.
    """
    host_controller: Optional[HostController] = Field(None, alias="HostController")
    """
    The entity that controls the bus.
    """
    voltage_tenths_volts: Optional[int] = Field(None, alias="VoltageTenthsVolts")
    """
    The voltage needed to drive this USB bus.
    """
    required_power_state: Optional[RequiredPowerState] = Field(None, alias="RequiredPowerState")
    description: Optional[str] = Field(None, alias="Description")
    """
    A description of the intended usage for this bus.
    """
    segments: Optional[List[Segment5]] = Field(None, alias="Segments")
    """
    Information about segments for this USB bus.
    """


class Connectors(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    so_cs: Optional[List[ConnectorsSOCs]] = Field(None, alias="SOCs")
    memory_subsystems: Optional[List[ConnectorsMemorySubsystem]] = Field(None, alias="MemorySubsystems")
    composites: Optional[List[ConnectorsComposite]] = Field(None, alias="Composites")
    cooling_subsystems: Optional[List[ConnectorsCoolingSubsystem]] = Field(None, alias="CoolingSubsystems")
    drives: Optional[List[ConnectorsDrive]] = Field(None, alias="Drives")
    mxios: Optional[List[ConnectorsMxio]] = Field(None, alias="Mxios")
    mpics: Optional[List[ConnectorsMpic]] = Field(None, alias="Mpics")
    ocp_mezzanine_slots: Optional[List[ConnectorsOCPMezzanineSlot]] = Field(None, alias="OCPMezzanineSlots")
    power_supplies: Optional[List[ConnectorsPowerSupply]] = Field(None, alias="PowerSupplies")
    control_panels: Optional[List[ConnectorsControlPanel]] = Field(None, alias="ControlPanels")
    pc_ie_ce_ms: Optional[List[ConnectorsPCIeCEM]] = Field(None, alias="PCIe_CEMs")
    power_distribution_board_managements: Optional[List[ConnectorsPowerDistributionBoardManagement]] = Field(
        None, alias="PowerDistributionBoardManagements"
    )
    real_time_clock_batteries: Optional[List[ConnectorsRealTimeClockBattery]] = Field(
        None, alias="RealTimeClockBatteries"
    )
    fans: Optional[List[ConnectorsFan]] = Field(None, alias="Fans")
    sc_is: Optional[List[ConnectorsSCI]] = Field(None, alias="SCIs")
    intrusion_detection: Optional[List[ConnectorsIntrusionDetection]] = Field(None, alias="IntrusionDetection")
    physical_us_bs: Optional[List[ConnectorsPhysicalUSB]] = Field(None, alias="PhysicalUSBs")
    oem: Optional[List[ConnectorsOEM]] = Field(None, alias="OEM")
    """
    Provides information for an OEM-specific connector.
    """


class Buses(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    display_port: Optional[List[BusesDisplayPort]] = Field(None, alias="DisplayPort")
    espi: Optional[List[BusesESPI]] = Field(None, alias="ESPI")
    i2_c: Optional[List[BusesI2C]] = Field(None, alias="I2C")
    i3_c: Optional[List[BusesI3C]] = Field(None, alias="I3C")
    jtag: Optional[List[BusesJTAG]] = Field(None, alias="JTAG")
    ltpi: Optional[List[BusesLTPI]] = Field(None, alias="LTPI")
    mpesti: Optional[List[BusesMPESTI]] = Field(None, alias="MPESTI")
    ncsi_rbt: Optional[List[BusesNCSIRBT]] = Field(None, alias="NCSI_RBT")
    pc_ie: Optional[List[BusesPCIe]] = Field(None, alias="PCIe")
    peci: Optional[List[BusesPECI]] = Field(None, alias="PECI")
    qspi: Optional[List[BusesQSPI]] = Field(None, alias="QSPI")
    sgmii: Optional[List[BusesSGMII]] = Field(None, alias="SGMII")
    spi: Optional[List[BusesSPI]] = Field(None, alias="SPI")
    sgpio: Optional[List[BusesSGPIO]] = Field(None, alias="SGPIO")
    uart: Optional[List[BusesUART]] = Field(None, alias="UART")
    usb: Optional[List[BusesUSB]] = Field(None, alias="USB")
    oem: Optional[List[Dict[str, Any]]] = Field(None, alias="OEM")
    """
    Provides information for an OEM-specific bus.
    """


class Component(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    component_class: Optional[ComponentClass] = Field(None, alias="ComponentClass")
    """
    The type of hardware that this component represents.
    """
    component_subclass: Optional[str] = Field(None, alias="ComponentSubclass")
    """
    The subtype of hardware that this component represents, such as DNO, FLW, or SDNO for an HPM.
    """
    vendor_id: Optional[constr(pattern=r"^([a-fA-F0-9]){4}$")] = Field(None, alias="VendorID")
    """
    The vendor ID assigned by the manufacturer for this component.
    """
    unique_id: Optional[str] = Field(None, alias="UniqueID")
    """
    A unique ID assigned by the manufacturer for this component, such as a PCIe DeviceID.
    """
    power_policy: Optional[PowerPolicy] = Field(None, alias="PowerPolicy")
    """
    The minimum system power state in which the component can be powered for full operation.
    """
    maximum_power_watts: Optional[int] = Field(None, alias="MaximumPowerWatts")
    """
    The maximum wattage that the component can draw when fully powered.
    """
    connectors: Optional[Connectors] = Field(None, alias="Connectors")
    devices: Optional[Devices] = Field(None, alias="Devices")
    buses: Optional[Buses] = Field(None, alias="Buses")


class HardwareComponent(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    field_comment: Optional[str] = Field(None, alias="_comment")
    """
    A general comment about a data file
    """
    copyright: Optional[str] = Field(None, alias="Copyright")
    """
    A copyright statement for the FRU data.
    """
    version: Optional[str] = Field(None, alias="Version")
    """
    The current file version for this FRU data.
    """
    schema_version: Optional[str] = Field(None, alias="SchemaVersion")
    """
    The revision of the HardwareComponent schema that this FRU data was built against.
    """
    author: Optional[str] = Field(None, alias="Author")
    """
    The author of this FRU data.
    """
    component: Optional[Component] = Field(None, alias="Component")
    """
    Information about a hardware component.
    """


class Model(RootModel[HardwareComponent]):
    root: HardwareComponent
