# generated by datamodel-codegen:
#   filename:  hardware-component-v0_5_6.json
#   timestamp: 2025-10-27T16:04:39+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field, RootModel, StringConstraints


class ComponentClass(Enum):
    hpm = "HPM"
    riser = "Riser"
    backplane = "Backplane"
    power_distribution_board = "PowerDistributionBoard"
    other = "Other"


class PowerPolicy(Enum):
    g3 = "G3"
    pre_stby = "Pre-STBY"
    stby = "STBY"
    s5 = "S5"
    s0 = "S0"


class MemoryTechnology(Enum):
    ddr4 = "DDR4"
    ddr5 = "DDR5"
    ddr6 = "DDR6"
    other = "Other"


class Proximity(Enum):
    near = "Near"
    far = "Far"


class FormFactor(Enum):
    sff = "SFF"
    tsff = "TSFF"
    other = "Other"


class Direction(Enum):
    upstream = "Upstream"
    downstream = "Downstream"


class CommonCircuitType(Enum):
    single_node = "Single Node"
    dual_node = "Dual Node"
    other = "Other"


class ConnectorType(Enum):
    a = "A"
    c = "C"
    other = "other"


class Destination(Enum):
    internal = "Internal"
    external = "External"


class AlertUsage(Enum):
    embedded = "Embedded"
    discrete = "Discrete"


class Density(Enum):
    quad = "Quad"
    dual = "Dual"
    single = "Single"


class IoType(Enum):
    push_pull = "push-pull"
    open_drain = "open drain"
    open_collector = "open collector"


class ProtocolType(Enum):
    basic = "Basic"
    standard = "Standard"


class TargetPortMode(Enum):
    basic = "Basic"
    standard = "Standard"


class Polarity(Enum):
    active_high = "active_high"
    active_low = "active_low"


class IsolationControlItem(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    signal: str = Field(alias="Signal")
    """
    The signal that controls this isolation mechanism.
    """
    polarity: Polarity = Field(alias="Polarity")
    """
    The polarity of the signal that controls this isolation mechanism.
    """


class Root(Enum):
    host = "Host"
    bmc = "BMC"
    other = "Other"


class Type(Enum):
    device = "Device"
    bridge = "Bridge"
    switch = "Switch"


class HostController(Enum):
    host = "Host"
    bmc = "BMC"


class NamedComponent(RootModel[str]):
    root: str
    """
    A component that is named so as to be referenceable.
    """


class ComponentAlias(RootModel[str]):
    root: str
    """
    A secondary reference name for a component.
    """


class AttachedConnectorListItem(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    type: str | None = Field(None, alias="Type")
    """
    The type of connector for this reference.
    """
    chip_select: float | None = Field(None, alias="ChipSelect")
    """
    The chip selection pin needed to access this device. This is primarily intended for use with ESPI, QSPI and SPI bus connections.
    """
    endpoint: str = Field(alias="Endpoint")
    """
    The endpoint connector for this reference.
    """
    mmbi_capable: bool | None = Field(None, alias="MMBICapable")
    """
    Whether the connector supports MMBI via the attached bus.
    """


class AttachedConnectorList(RootModel[list[AttachedConnectorListItem]]):
    root: list[AttachedConnectorListItem]
    """
    A collection of references to connectors attached to a bus.
    """


class ConnectedDeviceListItem(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    endpoint: str = Field(alias="Endpoint")
    """
    This instance of a connected device.
    """
    alias: ComponentAlias | None = Field(None, alias="Alias")
    address: str | None = Field(None, alias="Address")
    """
    The bus-specific hardware address needed to access a connected device, such as an I2C address.
    """
    random_access_capable: bool | None = Field(None, alias="RandomAccessCapable")
    """
    Indicates whether the BMC can access memory on this device in random fashion through this connection.
    """
    chip_select: float | None = Field(None, alias="ChipSelect")
    """
    The chip selection pin needed to access this device. This is primarily intended for use with ESPI, QSPI and SPI bus connections.
    """


class ConnectedDeviceList(RootModel[list[ConnectedDeviceListItem]]):
    root: list[ConnectedDeviceListItem]
    """
    Information about devices connected to a bus.
    """


class PhysicalLocation(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    upper_x_mils: int = Field(alias="UpperXMils")
    """
    The upper x-axis corner of the bounding box surrounding the component, in millimeters.
    """
    upper_y_mils: int = Field(alias="UpperYMils")
    """
    The upper y-axis corner of the bounding box surrounding the component, in millimeters.
    """
    lower_x_mils: int = Field(alias="LowerXMils")
    """
    The lower x-axis corner of the bounding box surrounding the component, in millimeters.
    """
    lower_y_mils: int = Field(alias="LowerYMils")
    """
    The lower y-axis corner of the bounding box surrounding the component, in millimeters.
    """


class SilkscreenName(RootModel[str]):
    root: str
    """
    The name silkscreened onto the HPM board for the component.
    """


class ReferenceDesignator(RootModel[str]):
    root: str
    """
    The reference designator used to logically describe the component in the BOM list.
    """


class RequiredPowerState(Enum):
    g3 = "G3"
    pre_stby = "Pre-STBY"
    stby = "STBY"
    s5 = "S5"
    s0 = "S0"
    other = "Other"


class Models(RootModel[list[str]]):
    root: list[str]
    """
    The possible models for this component.
    """


class Manufacturers(RootModel[list[str]]):
    root: list[str]
    """
    The possible manufacturers for this component.
    """


class Endpoint(RootModel[str]):
    root: str
    """
    An endpoint attached to this component.
    """


class MUXChannelConfigItem(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    mux_pin: str = Field(alias="MUXPin")
    """
    A pin needed to select this MUX channel.
    """
    setting: float = Field(alias="Setting")
    """
    The setting needed on a pin to select this MUX channel.
    """


class MUXChannelConfig(RootModel[list[MUXChannelConfigItem]]):
    root: list[MUXChannelConfigItem]
    """
    Information about selecting a channel in a MUX.
    """


class Signal1(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    type: str | None = Field(None, alias="Type")
    """
    The type locating the signal used to control the pin.
    """
    type_id: str | None = Field(None, alias="TypeID")
    """
    The specific device housing the signal used to control the pin.
    """
    subtype: str | None = Field(None, alias="Subtype")
    """
    The subtype locating the signal used to control the pina pin.
    """
    subtype_id: str | None = Field(None, alias="SubtypeID")
    """
    The specific signal used to control the pin.
    """


class MUXControlItem(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    mux_pin: str = Field(alias="MUXPin")
    """
    A pin used to control this MUX channel.
    """
    signal: Signal1 = Field(alias="Signal")
    """
    The signal used to control the pin.
    """


class MUXControl(RootModel[list[MUXControlItem]]):
    root: list[MUXControlItem]
    """
    Information about mechanisms used to control this MUX.
    """


class Signal(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    connector_name: str | None = Field(None, alias="ConnectorName")
    """
    The name of the signal as defined by a connector.
    """
    alias: ComponentAlias | None = Field(None, alias="Alias")
    type: str | None = Field(None, alias="Type")
    """
    The type for this physical signal.
    """
    type_id: NamedComponent | None = Field(None, alias="TypeID")
    subtype: str | None = Field(None, alias="Subtype")
    """
    The connector subtype for this physical signal.
    """
    subtype_id: NamedComponent | None = Field(None, alias="SubtypeID")
    physical_pin: str = Field(alias="PhysicalPin")
    """
    The physical pin for this physical signal reference.
    """
    netlist_name: str | None = Field(None, alias="NetlistName")
    """
    The Netlist name for this physical signal reference.
    """


class ConnectorsComposite(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    connector_type: str = Field(alias="ConnectorType")
    """
    The type of the composite.
    """
    data_file: str | None = Field(None, alias="DataFile")
    """
    The data file with JSON information specific to this composite.
    """
    silkscreen_name: SilkscreenName | None = Field(None, alias="SilkscreenName")
    reference_designator: ReferenceDesignator = Field(alias="ReferenceDesignator")
    mpics: list[str] = Field(alias="MPICs")
    """
    The MPICs used by the composite.
    """
    mxios: list[str] = Field(alias="MXIOs")
    """
    The MXIOs used by the composite.
    """
    physical_location: PhysicalLocation | None = Field(None, alias="PhysicalLocation")


class FlexIO(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    netlist_name: str | None = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this FLEXIO.
    """


class Sideband(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    netlist_name: str | None = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this sideband.
    """


class BusesDisplayPort(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    netlist_name: str | None = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this bus.
    """
    connected_devices: ConnectedDeviceList | None = Field(None, alias="ConnectedDevices")
    connectors: AttachedConnectorList | None = Field(None, alias="Connectors")


class BusesESPI(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    netlist_name: str | None = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this bus.
    """
    max_clock_speed_m_hz: int = Field(alias="MaxClockSpeedMHz")
    """
    The maximum clock speed for this ESPI bus.
    """
    alert_usage: AlertUsage | None = Field(None, alias="AlertUsage")
    """
    The manner in which alerts are signaled on the bus.
    """
    density: Density = Field(alias="Density")
    """
    The data transfer mode supported by this ESPI bus.
    """
    controller: str | None = Field(None, alias="Controller")
    """
    The component that receives interrupt requests and controls this bus.
    """
    connected_devices: ConnectedDeviceList | None = Field(None, alias="ConnectedDevices")
    connectors: AttachedConnectorList | None = Field(None, alias="Connectors")


class Channel(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    voltage_tenths_volts: int | None = Field(None, alias="VoltageTenthsVolts")
    """
    The voltage needed to drive this MUX channel.
    """
    io_type: IoType = Field(alias="IOType")
    """
    The type of I/O used for this MUX channel.
    """
    mux_config: MUXChannelConfig = Field(alias="MUXConfig")
    endpoint: Endpoint = Field(alias="Endpoint")


class MuX(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    channels: list[Channel] = Field(alias="Channels")
    """
    Information about I2C MUXes in this I2C segment.
    """
    propagation_delay_ns: int | None = Field(None, alias="PropagationDelayNS")
    """
    The propagation delay for this MUX.
    """
    address: str | None = Field(None, alias="Address")
    """
    The I2C address for this MUX.
    """
    models: Models | None = Field(None, alias="Models")
    manufacturers: Manufacturers = Field(alias="Manufacturers")
    isolation_capable: bool | None = Field(None, alias="IsolationCapable")
    """
    Indicates whether the MUX can isolate voltage for channels.
    """
    rise_time_ns: int | None = Field(None, alias="RiseTimeNS")
    """
    The rise time for this MUX.
    """
    fall_time_ns: int | None = Field(None, alias="FallTimeNS")
    """
    The fall time for this MUX.
    """
    control: MUXControl | None = Field(None, alias="Control")
    silkscreen_name: SilkscreenName | None = Field(None, alias="SilkscreenName")
    reference_designator: ReferenceDesignator = Field(alias="ReferenceDesignator")
    description: str | None = Field(None, alias="Description")
    """
    A description of the intended usage for this MUX.
    """
    physical_location: PhysicalLocation | None = Field(None, alias="PhysicalLocation")


class Port(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    voltage_tenths_volts: int | None = Field(None, alias="VoltageTenthsVolts")
    """
    The voltage needed to drive this I3C port.
    """
    target_port_mode: TargetPortMode | None = Field(None, alias="TargetPortMode")
    """
    The target mode for this I3C port.
    """
    endpoint: Endpoint = Field(alias="Endpoint")
    description: str | None = Field(None, alias="Description")
    """
    A description of the intended usage for this port.
    """


class Hub(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    ports: list[Port] = Field(alias="Ports")
    """
    Information about I3C ports.
    """
    propagation_delay_ns: int | None = Field(None, alias="PropagationDelayNS")
    """
    The propagation delay for an I3C Hub.
    """
    address: str | None = Field(None, alias="Address")
    """
    The I3C address at which this hub responds.
    """
    models: Models | None = Field(None, alias="Models")
    manufacturers: Manufacturers = Field(alias="Manufacturers")
    silkscreen_name: SilkscreenName | None = Field(None, alias="SilkscreenName")
    reference_designator: ReferenceDesignator = Field(alias="ReferenceDesignator")
    description: str | None = Field(None, alias="Description")
    """
    A description of the intended usage for this hub.
    """


class Channel1(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    voltage_tenths_volts: int | None = Field(None, alias="VoltageTenthsVolts")
    """
    The voltage needed to drive this MUX channel.
    """
    mux_config: MUXChannelConfig = Field(alias="MUXConfig")
    endpoint: Endpoint = Field(alias="Endpoint")


class MuX1(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    channels: list[Channel1] = Field(alias="Channels")
    """
    Information about channels in this I3C MUX.
    """
    control: MUXControl | None = Field(None, alias="Control")
    propagation_delay_ns: int | None = Field(None, alias="PropagationDelayNS")
    """
    The propagation delay for this MUX.
    """
    address: str | None = Field(None, alias="Address")
    """
    The I3C address for this MUX.
    """
    models: Models | None = Field(None, alias="Models")
    manufacturers: Manufacturers = Field(alias="Manufacturers")
    level_shifting_capable: bool | None = Field(None, alias="LevelShiftingCapable")
    """
    Indicates whether the MUX can shift between voltage levels.
    """
    fault_detection_capable: bool | None = Field(None, alias="FaultDetectionCapable")
    """
    Indicates whether the MUX can detect faults.
    """
    fault_clear_signal_capable: bool | None = Field(None, alias="FaultClearSignalCapable")
    """
    Indicates whether the MUX can utilize a fault clear signal.
    """
    rise_time_ns: int | None = Field(None, alias="RiseTimeNS")
    """
    The rise time for this MUX.
    """
    fall_time_ns: int | None = Field(None, alias="FallTimeNS")
    """
    The fall time for this MUX.
    """
    silkscreen_name: SilkscreenName | None = Field(None, alias="SilkscreenName")
    reference_designator: ReferenceDesignator = Field(alias="ReferenceDesignator")
    description: str | None = Field(None, alias="Description")
    """
    A description of the intended usage for this MUX.
    """
    physical_location: PhysicalLocation | None = Field(None, alias="PhysicalLocation")


class Segment1(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    netlist_name: str | None = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this segment.
    """
    hubs: list[Hub] | None = Field(None, alias="Hubs")
    """
    Information about I3C hubs.
    """
    muxes: list[MuX1] | None = Field(None, alias="MUXes")
    """
    Information about I3C MUXes.
    """
    connected_devices: ConnectedDeviceList | None = Field(None, alias="ConnectedDevices")
    connectors: AttachedConnectorList | None = Field(None, alias="Connectors")


class BusesI3C(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    netlist_name: str | None = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this bus.
    """
    protocol_type: ProtocolType = Field(alias="ProtocolType")
    """
    The protocol type for this I3C bus.
    """
    voltage_tenths_volts: int | None = Field(None, alias="VoltageTenthsVolts")
    """
    The voltage needed to drive this I3C bus.
    """
    required_power_state: RequiredPowerState = Field(alias="RequiredPowerState")
    frequency_k_hz: int = Field(alias="FrequencyKHz")
    """
    The frequency at which this I3C bus shall operate.
    """
    segments: list[Segment1] = Field(alias="Segments")
    """
    Information about I3C segments.
    """


class Channel2(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    endpoint: Endpoint = Field(alias="Endpoint")
    mux_config: MUXChannelConfig = Field(alias="MUXConfig")
    description: str | None = Field(None, alias="Description")
    """
    A description for this JTAG MUX channel.
    """


class MuX2(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    channels: list[Channel2] = Field(alias="Channels")
    """
    Information about channels in a JTAG MUX.
    """


class Segment2(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    muxes: list[MuX2] | None = Field(None, alias="MUXes")
    """
    Information about MUXes in a JTAG segment.
    """
    control: MUXControl | None = Field(None, alias="Control")
    connected_devices: ConnectedDeviceList | None = Field(None, alias="ConnectedDevices")
    connectors: AttachedConnectorList | None = Field(None, alias="Connectors")


class BusesJTAG(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    netlist_name: str | None = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this bus.
    """
    segments: list[Segment2] = Field(alias="Segments")
    """
    Information about JTAG segments.
    """


class BusesLTPI(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    netlist_name: str | None = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this bus.
    """
    required_power_state: RequiredPowerState = Field(alias="RequiredPowerState")
    max_clock_speed_m_hz: int = Field(alias="MaxClockSpeedMHz")
    """
    The maximum clock speed for this LTPI bus.
    """
    connected_devices: ConnectedDeviceList | None = Field(None, alias="ConnectedDevices")
    connectors: AttachedConnectorList | None = Field(None, alias="Connectors")


class BusesMPESTI(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    netlist_name: str | None = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this bus.
    """
    connected_devices: ConnectedDeviceList | None = Field(None, alias="ConnectedDevices")
    connectors: AttachedConnectorList | None = Field(None, alias="Connectors")


class Channel3(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    endpoint: str = Field(alias="Endpoint")
    """
    The endpoint to which this channel is connnected.
    """


class Isolation(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    channels: list[Channel3] = Field(alias="Channels")
    """
    Information about channels for isolation management.
    """
    isolation_control: list[IsolationControlItem] = Field(alias="IsolationControl")
    """
    Information about control for isolation management.
    """


class Segment3(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    netlist_name: str | None = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this segment.
    """
    isolation: Isolation | None = Field(None, alias="Isolation")
    """
    Information about isolation management for this NC-SI RBT bus.
    """
    connected_devices: ConnectedDeviceList | None = Field(None, alias="ConnectedDevices")
    connectors: AttachedConnectorList | None = Field(None, alias="Connectors")


class BusesNCSIRBT(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    netlist_name: str | None = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this bus.
    """
    segments: list[Segment3] = Field(alias="Segments")
    """
    Information about segments for this NC-SI RBT bus.
    """


class Component1(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    type: Type | None = Field(None, alias="Type")
    """
    The type of this PCIe component.
    """
    version: int = Field(alias="Version")
    """
    The highest version of the PCIe specification supported by this PCIe component.
    """
    vendor_id: str = Field(alias="VendorID")
    """
    The PCIe vendor ID for this PCIe component.
    """
    subvendor_id: str = Field(alias="SubvendorID")
    """
    The PCIe subvendor ID for this PCIe component.
    """
    device_id: str = Field(alias="DeviceID")
    """
    The PCIe device ID for this PCIe component.
    """
    subdevice_id: str = Field(alias="SubdeviceID")
    """
    The PCIe subdevice ID for this PCIe component.
    """
    root_port: str = Field(alias="RootPort")
    """
    The root port associated with this PCIe component.
    """
    width: str = Field(alias="Width")
    """
    The width, in PCIe lanes, for this PCIe component.
    """
    lane_mapping: list[int] = Field(alias="LaneMapping")
    """
    The mapping of lanes for this PCIe component.
    """
    hot_plug_supported: bool = Field(alias="HotPlugSupported")
    """
    Indicates whether the PCIe component is hot-pluggable.
    """
    dma_supported: bool = Field(alias="DMASupported")
    """
    Indicates whether the PCIe component supports direct memory access.
    """
    cxl_supported: bool = Field(alias="CxlSupported")
    """
    Indicates whether the PCIe component supports Compute Express Link (CXL).
    """
    cxl_version_minimum: str = Field(alias="CxlVersionMinimum")
    """
    The maximum version of the CXL specification supported by this PCIe component.
    """
    link_speed_supported_maximum_gb_per_sec: int = Field(alias="LinkSpeedSupportedMaximumGBPerSec")
    """
    The maximum link speed supported by this PCIe component.
    """
    bifurcation_capable: bool = Field(alias="BifurcationCapable")
    """
    Indicates whether the PCIe component supports bifurcation of its PCIe lanes.
    """
    bifurcation_minimum: int = Field(alias="BifurcationMinimum")
    """
    The minimum lane width supported by this PCIe component for bifurcation.
    """
    ports: int = Field(alias="Ports")
    """
    The number of PCIe ports supported by this PCIe switch.
    """
    latency_ns: int = Field(alias="LatencyNS")
    """
    The latency of this PCIe switch.
    """
    models: Models | None = Field(None, alias="Models")
    manufacturers: Manufacturers | None = Field(None, alias="Manufacturers")
    silkscreen_name: SilkscreenName | None = Field(None, alias="SilkscreenName")
    reference_designator: ReferenceDesignator = Field(alias="ReferenceDesignator")
    physical_location: PhysicalLocation | None = Field(None, alias="PhysicalLocation")
    endpoint: Endpoint = Field(alias="Endpoint")


class Fabric(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    netlist_name: str | None = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this fabric.
    """
    host_soc_root_port: str | None = Field(None, alias="HostSOCRootPort")
    """
    The assigned port for the SOC PCIe root complex enumeration.
    """
    first_lane: int | None = Field(None, alias="FirstLane")
    """
    The first PCIe lane used for this fabric.
    """
    width: int | None = Field(None, alias="Width")
    """
    The number of PCIe lanes used for this fabric.
    """
    components: list[Component1] | None = Field(None, alias="Components")
    """
    Information about PCIe components in a PCIe bus.
    """
    connected_devices: ConnectedDeviceList | None = Field(None, alias="ConnectedDevices")
    connectors: AttachedConnectorList | None = Field(None, alias="Connectors")


class BusesPCIe(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    netlist_name: str | None = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this bus.
    """
    lanes: int = Field(alias="Lanes")
    """
    The number of PCIe lanes for this bus.
    """
    version: float = Field(alias="Version")
    """
    The highest generation version of PCIe supported by this bus.
    """
    root: Root = Field(alias="Root")
    """
    The location of the PCIe root.
    """
    fabric: Fabric = Field(alias="Fabric")
    """
    Information about PCIe bus fabrics.
    """


class BusesPECI(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    netlist_name: str | None = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this bus.
    """
    connected_devices: ConnectedDeviceList | None = Field(None, alias="ConnectedDevices")
    connectors: AttachedConnectorList | None = Field(None, alias="Connectors")


class BusesQSPI(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    netlist_name: str | None = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this bus.
    """
    max_clock_speed_m_hz: int = Field(alias="MaxClockSpeedMHz")
    """
    The maximum clock speed for this QSPI bus.
    """
    density: Density = Field(alias="Density")
    """
    The data transfer mode supported by this ESPI bus.
    """
    controller: str | None = Field(None, alias="Controller")
    """
    The component that receives interrupt requests and controls this bus.
    """
    connected_devices: ConnectedDeviceList | None = Field(None, alias="ConnectedDevices")
    connectors: AttachedConnectorList | None = Field(None, alias="Connectors")


class BusesSGMII(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    netlist_name: str | None = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this bus.
    """
    connected_devices: ConnectedDeviceList | None = Field(None, alias="ConnectedDevices")
    connectors: AttachedConnectorList | None = Field(None, alias="Connectors")


class BusesSPI(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    netlist_name: str | None = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this bus.
    """
    max_clock_speed_m_hz: int = Field(alias="MaxClockSpeedMHz")
    """
    The maximum clock speed for this SPI bus.
    """
    alert_usage: AlertUsage | None = Field(None, alias="AlertUsage")
    """
    The manner in which alerts are signaled on the bus.
    """
    density: Density = Field(alias="Density")
    """
    The data transfer mode supported by this ESPI bus.
    """
    interrupt_request: str | None = Field(None, alias="InterruptRequest")
    """
    Indicates the component to which the IRQ[0] pin is connected.
    """
    controller: str | None = Field(None, alias="Controller")
    """
    The component that receives interrupt requests and controls this bus.
    """
    connected_devices: ConnectedDeviceList | None = Field(None, alias="ConnectedDevices")
    connectors: AttachedConnectorList | None = Field(None, alias="Connectors")


class BusesSGPIO(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    netlist_name: str | None = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this bus.
    """
    connected_devices: ConnectedDeviceList | None = Field(None, alias="ConnectedDevices")
    connectors: AttachedConnectorList | None = Field(None, alias="Connectors")


class Channel4(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    endpoint: Endpoint = Field(alias="Endpoint")
    mux_config: MUXChannelConfig = Field(alias="MUXConfig")


class MuX3(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    propagation_delay_ns: int | None = Field(None, alias="PropagationDelayNS")
    """
    The propagation delay for this UART MUX.
    """
    channels: list[Channel4] = Field(alias="Channels")
    """
    Information about channels in a UART MUX.
    """
    control: MUXControl | None = Field(None, alias="Control")
    silkscreen_name: SilkscreenName | None = Field(None, alias="SilkscreenName")
    reference_designator: ReferenceDesignator = Field(alias="ReferenceDesignator")
    physical_location: PhysicalLocation | None = Field(None, alias="PhysicalLocation")


class Segment4(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    muxes: list[MuX3] | None = Field(None, alias="MUXes")
    """
    Information about MUXes in a UART segment.
    """
    connected_devices: ConnectedDeviceList | None = Field(None, alias="ConnectedDevices")
    connectors: AttachedConnectorList | None = Field(None, alias="Connectors")


class BusesUART(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    netlist_name: str | None = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this bus.
    """
    voltage_tenths_volts: int | None = Field(None, alias="VoltageTenthsVolts")
    """
    The voltage needed to drive this UART bus.
    """
    required_power_state: RequiredPowerState = Field(alias="RequiredPowerState")
    segments: list[Segment4] = Field(alias="Segments")
    """
    Information about UART segments.
    """


class MuX4(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    propagation_delay_ns: int | None = Field(None, alias="PropagationDelayNS")
    """
    The propagation delay for this MUX.
    """
    channels: list[Channel4] = Field(alias="Channels")
    """
    Information about channels in this MUX.
    """
    control: MUXControl | None = Field(None, alias="Control")
    silkscreen_name: SilkscreenName | None = Field(None, alias="SilkscreenName")
    reference_designator: ReferenceDesignator = Field(alias="ReferenceDesignator")
    physical_location: PhysicalLocation | None = Field(None, alias="PhysicalLocation")


class Port1(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    voltage_tenths_volts: int | None = Field(None, alias="VoltageTenthsVolts")
    """
    The voltage needed to drive this USB port.
    """
    endpoint: Endpoint = Field(alias="Endpoint")


class Hub1(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    ports: list[Port1] = Field(alias="Ports")
    """
    Information about ports for this USB bus hub.
    """
    models: Models | None = Field(None, alias="Models")
    manufacturers: Manufacturers | None = Field(None, alias="Manufacturers")
    silkscreen_name: SilkscreenName | None = Field(None, alias="SilkscreenName")
    reference_designator: ReferenceDesignator = Field(alias="ReferenceDesignator")
    description: str | None = Field(None, alias="Description")
    """
    A description of the intended usage for this hub.
    """
    physical_location: PhysicalLocation | None = Field(None, alias="PhysicalLocation")


class ReferencedBusListItem(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    type: str | None = Field(None, alias="Type")
    """
    The type of bus for this reference.
    """
    identifier: str = Field(alias="Identifier")
    """
    The instance of the bus type for this reference.
    """
    spec_bus_name: str | None = Field(None, alias="SpecBusName")
    """
    The name used in the spec to reference this bus.
    """
    signals: list[Signal] | None = Field(None, alias="Signals")
    """
    Information about the signals for this referenced bus.
    """


class ReferencedBusList(RootModel[list[ReferencedBusListItem]]):
    root: list[ReferencedBusListItem]
    """
    A collection of references to hardware or logical buses as defined in the buses section of this document.
    """


class ConnectorsSOCs(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    vendor_name: str = Field(alias="VendorName")
    """
    The name of the vendor of the SOC.
    """
    vendor_id: str = Field(alias="VendorID")
    """
    The PCIe VendorID for the vendor of the SOC.
    """
    connector_type: str = Field(alias="ConnectorType")
    """
    The type of the SOC.
    """
    silkscreen_name: SilkscreenName | None = Field(None, alias="SilkscreenName")
    reference_designator: ReferenceDesignator = Field(alias="ReferenceDesignator")
    dimm_channels_supported: int = Field(alias="DimmChannelsSupported")
    """
    The number of dimm channels supported by the SOC.
    """
    physical_location: PhysicalLocation | None = Field(None, alias="PhysicalLocation")
    models: Models | None = Field(None, alias="Models")
    manufacturers: Manufacturers | None = Field(None, alias="Manufacturers")
    connected_buses: ReferencedBusList | None = Field(None, alias="ConnectedBuses")


class Slot(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    proximity: Proximity = Field(alias="Proximity")
    """
    The proximity of the memory subsystem slot to its associated SOC.
    """
    silkscreen_name: SilkscreenName | None = Field(None, alias="SilkscreenName")
    reference_designator: ReferenceDesignator = Field(alias="ReferenceDesignator")
    associated_soc: str = Field(alias="AssociatedSOC")
    """
    The SOC associated with this memory subsystem slot.
    """
    physical_location: PhysicalLocation | None = Field(None, alias="PhysicalLocation")
    connected_buses: ReferencedBusList | None = Field(None, alias="ConnectedBuses")


class ConnectorsMemorySubsystem(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    channel_count: int = Field(alias="ChannelCount")
    """
    The number of channels supported by the memory subsystem.
    """
    slots_per_channel: int | list[int] = Field(alias="SlotsPerChannel")
    """
    The number of slots in each channel supported by the memory subsystem.
    """
    memory_technology: MemoryTechnology = Field(alias="MemoryTechnology")
    """
    The memory technology supported by the memory subsystem.
    """
    slots: list[Slot] = Field(alias="Slots")
    """
    Information about an individual channels slot in the memory subsystem.
    """


class ConnectorsCoolingSubsystem(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    silkscreen_name: SilkscreenName | None = Field(None, alias="SilkscreenName")
    reference_designator: ReferenceDesignator = Field(alias="ReferenceDesignator")
    maximum_power_watts: int = Field(alias="MaximumPowerWatts")
    """
    The maximum power for this cooling subsystem.
    """
    connected_buses: ReferencedBusList | None = Field(None, alias="ConnectedBuses")
    models: Models | None = Field(None, alias="Models")
    manufacturers: Manufacturers | None = Field(None, alias="Manufacturers")
    physical_location: PhysicalLocation | None = Field(None, alias="PhysicalLocation")


class ConnectorsDrive(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    silkscreen_name: SilkscreenName | None = Field(None, alias="SilkscreenName")
    reference_designator: ReferenceDesignator = Field(alias="ReferenceDesignator")
    drive_type: str = Field(alias="DriveType")
    """
    The specific connector type for this drive, such as EDSFF or M.2.
    """
    connected_buses: ReferencedBusList | None = Field(None, alias="ConnectedBuses")
    models: Models | None = Field(None, alias="Models")
    manufacturers: Manufacturers | None = Field(None, alias="Manufacturers")
    physical_location: PhysicalLocation | None = Field(None, alias="PhysicalLocation")


class ConnectorsMxio(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    soc_socket_association: str | None = Field(None, alias="SOCSocketAssociation")
    """
    The SOC Socket to which this MXIO is connected.
    """
    common_clocking_support: bool | None = Field(None, alias="CommonClockingSupport")
    """
    Indicates whether the MXIO supports common clocking.
    """
    connector_type: str = Field(alias="ConnectorType")
    """
    The type of connector for this MXIO.
    """
    connected_buses: ReferencedBusList | None = Field(None, alias="ConnectedBuses")
    silkscreen_name: SilkscreenName | None = Field(None, alias="SilkscreenName")
    reference_designator: ReferenceDesignator = Field(alias="ReferenceDesignator")
    flex_i_os: list[FlexIO] = Field(alias="FlexIOs")
    """
    The FlexIOs used by the MXIO.
    """
    signals: list[Signal] | None = Field(None, alias="Signals")
    """
    Information about the signals for this MXIO.
    """
    physical_location: PhysicalLocation | None = Field(None, alias="PhysicalLocation")


class ConnectorsMpic(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    connector_type: str = Field(alias="ConnectorType")
    """
    The type of connector for this MPIC.
    """
    adjusted_maximum_actual_power_supported_watts: int | None = Field(
        None, alias="AdjustedMaximumActualPowerSupportedWatts"
    )
    """
    The adjusted maximum actual power supported for this MPIC.
    """
    silkscreen_name: SilkscreenName | None = Field(None, alias="SilkscreenName")
    reference_designator: ReferenceDesignator = Field(alias="ReferenceDesignator")
    sidebands: list[Sideband] = Field(alias="Sidebands")
    """
    The sidebands used by the MPIC.
    """
    connected_buses: ReferencedBusList | None = Field(None, alias="ConnectedBuses")
    physical_location: PhysicalLocation | None = Field(None, alias="PhysicalLocation")


class ConnectorsPowerSupply(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    connector_type: str = Field(alias="ConnectorType")
    """
    The type of connector for this power supply.
    """
    silkscreen_name: SilkscreenName | None = Field(None, alias="SilkscreenName")
    reference_designator: ReferenceDesignator = Field(alias="ReferenceDesignator")
    hot_plug_supported: bool = Field(alias="HotPlugSupported")
    """
    Indicates whether the power supply supports hot plugging.
    """
    connected_buses: ReferencedBusList | None = Field(None, alias="ConnectedBuses")
    models: Models | None = Field(None, alias="Models")
    manufacturers: Manufacturers | None = Field(None, alias="Manufacturers")
    physical_location: PhysicalLocation | None = Field(None, alias="PhysicalLocation")


class ConnectorsOCPMezzanineSlot(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    version: str = Field(alias="Version")
    """
    The version of the OCP NIC specification with which this OCP mezzanine expansion slot complies.
    """
    silkscreen_name: SilkscreenName | None = Field(None, alias="SilkscreenName")
    reference_designator: ReferenceDesignator = Field(alias="ReferenceDesignator")
    form_factor: FormFactor = Field(alias="FormFactor")
    """
    The form factor for this OCP mezzanine expansion slot.
    """
    connected_buses: ReferencedBusList | None = Field(None, alias="ConnectedBuses")
    paired_slot_for_double_wide: str | None = Field(None, alias="PairedSlotForDoubleWide")
    """
    The slot with which this slot is paired for use as a double-wide connector in the DSFF or TDSFF form factor.
    """
    signals: list[Signal] | None = Field(None, alias="Signals")
    """
    Information about the signals for this OCP Mezzanine slot.
    """
    physical_location: PhysicalLocation | None = Field(None, alias="PhysicalLocation")


class ConnectorsControlPanel(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    silkscreen_name: SilkscreenName | None = Field(None, alias="SilkscreenName")
    reference_designator: ReferenceDesignator = Field(alias="ReferenceDesignator")
    primary: bool | None = Field(None, alias="Primary")
    """
    Indicates whether this is the primary control panel.
    """
    connected_buses: ReferencedBusList | None = Field(None, alias="ConnectedBuses")
    models: Models | None = Field(None, alias="Models")
    manufacturers: Manufacturers | None = Field(None, alias="Manufacturers")
    physical_location: PhysicalLocation | None = Field(None, alias="PhysicalLocation")


class ConnectorsPCIeCEM(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    connector_type: str = Field(alias="ConnectorType")
    """
    The type for this CEM slot.
    """
    silkscreen_name: SilkscreenName | None = Field(None, alias="SilkscreenName")
    reference_designator: ReferenceDesignator = Field(alias="ReferenceDesignator")
    connected_buses: ReferencedBusList | None = Field(None, alias="ConnectedBuses")
    signals: list[Signal] | None = Field(None, alias="Signals")
    """
    Information about the signals for this PCIe CEM slot.
    """
    physical_location: PhysicalLocation | None = Field(None, alias="PhysicalLocation")


class ConnectorsPowerDistributionBoardManagement(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    management_type: str = Field(alias="ManagementType")
    """
    The type of power distribution management board connector, such as type 1 or type 2.
    """
    connector_type: str = Field(alias="ConnectorType")
    """
    The connector type for this power distribution management board connector.
    """
    direction: Direction = Field(alias="Direction")
    """
    The intended linkage for this power distribution management board connector.
    """
    sidebands: list[Sideband] = Field(alias="Sidebands")
    """
    The sidebands used by the PDB.
    """
    silkscreen_name: SilkscreenName | None = Field(None, alias="SilkscreenName")
    reference_designator: ReferenceDesignator = Field(alias="ReferenceDesignator")
    connected_buses: ReferencedBusList | None = Field(None, alias="ConnectedBuses")
    models: Models | None = Field(None, alias="Models")
    manufacturers: Manufacturers | None = Field(None, alias="Manufacturers")
    physical_location: PhysicalLocation | None = Field(None, alias="PhysicalLocation")


class ConnectorsRealTimeClockBattery(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    silkscreen_name: SilkscreenName | None = Field(None, alias="SilkscreenName")
    reference_designator: ReferenceDesignator = Field(alias="ReferenceDesignator")
    physical_location: PhysicalLocation | None = Field(None, alias="PhysicalLocation")
    connected_buses: ReferencedBusList | None = Field(None, alias="ConnectedBuses")


class ConnectorsFan(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    pins: int = Field(alias="Pins")
    """
    The number of pins for the connector for this fan.
    """
    maximum_power_watts: int = Field(alias="MaximumPowerWatts")
    """
    The maximum power for this fan.
    """
    connector_type: str = Field(alias="ConnectorType")
    """
    The type of connector for this fan.
    """
    silkscreen_name: SilkscreenName | None = Field(None, alias="SilkscreenName")
    reference_designator: ReferenceDesignator = Field(alias="ReferenceDesignator")
    hot_plug_supported: bool = Field(alias="HotPlugSupported")
    """
    Indicates whether this fan supports hot plugging.
    """
    connected_buses: ReferencedBusList | None = Field(None, alias="ConnectedBuses")
    models: Models | None = Field(None, alias="Models")
    manufacturers: Manufacturers | None = Field(None, alias="Manufacturers")
    physical_location: PhysicalLocation | None = Field(None, alias="PhysicalLocation")


class ConnectorsSCI(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    revision: str = Field(alias="Revision")
    """
    The revision of this SCI.
    """
    version: str = Field(alias="Version")
    """
    The version of this SCI.
    """
    common_circuit_type: CommonCircuitType = Field(alias="CommonCircuitType")
    """
    The number of nodes supported by this SCI.
    """
    backup_battery_voltage_measurement_capable: bool | None = Field(
        None, alias="BackupBatteryVoltageMeasurementCapable"
    )
    """
    Indicates whether this SCI supports measurement of the backup battery voltage.
    """
    connected_buses: ReferencedBusList | None = Field(None, alias="ConnectedBuses")
    silkscreen_name: SilkscreenName | None = Field(None, alias="SilkscreenName")
    reference_designator: ReferenceDesignator = Field(alias="ReferenceDesignator")
    models: Models | None = Field(None, alias="Models")
    manufacturers: Manufacturers | None = Field(None, alias="Manufacturers")
    signals: list[Signal] | None = Field(None, alias="Signals")
    """
    Information about the signals for this SCI.
    """
    physical_location: PhysicalLocation | None = Field(None, alias="PhysicalLocation")


class ConnectorsIntrusionDetection(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    silkscreen_name: SilkscreenName | None = Field(None, alias="SilkscreenName")
    reference_designator: ReferenceDesignator = Field(alias="ReferenceDesignator")
    connector_type: str = Field(alias="ConnectorType")
    """
    The type of connector for this intrusion detection module.
    """
    status_signal_netname: str = Field(alias="StatusSignalNetname")
    """
    The netname of the signal that provides the state of the intrusion detection sensor.
    """
    models: Models | None = Field(None, alias="Models")
    manufacturers: Manufacturers | None = Field(None, alias="Manufacturers")
    physical_location: PhysicalLocation | None = Field(None, alias="PhysicalLocation")
    connected_buses: ReferencedBusList | None = Field(None, alias="ConnectedBuses")


class ConnectorsPhysicalUSB(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    silkscreen_name: SilkscreenName | None = Field(None, alias="SilkscreenName")
    reference_designator: ReferenceDesignator = Field(alias="ReferenceDesignator")
    connector_type: ConnectorType = Field(alias="ConnectorType")
    """
    The USB type of the connector for this physical USB port.
    """
    destination: Destination = Field(alias="Destination")
    """
    The endpoint location of this physical USB port.
    """
    connected_buses: ReferencedBusList | None = Field(None, alias="ConnectedBuses")
    models: Models | None = Field(None, alias="Models")
    manufacturers: Manufacturers | None = Field(None, alias="Manufacturers")
    physical_location: PhysicalLocation | None = Field(None, alias="PhysicalLocation")


class ConnectorsOEM(BaseModel):
    model_config = ConfigDict(extra="allow", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    silkscreen_name: SilkscreenName | None = Field(None, alias="SilkscreenName")
    reference_designator: ReferenceDesignator = Field(alias="ReferenceDesignator")
    connector_type: str = Field(alias="ConnectorType")
    """
    The type of this OEM connector.
    """
    connected_buses: ReferencedBusList | None = Field(None, alias="ConnectedBuses")
    models: Models | None = Field(None, alias="Models")
    manufacturers: Manufacturers | None = Field(None, alias="Manufacturers")
    physical_location: PhysicalLocation | None = Field(None, alias="PhysicalLocation")


class Device(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    type: str | None = Field(None, alias="Type")
    """
    The type of the device.
    """
    models: Models | None = Field(None, alias="Models")
    manufacturers: Manufacturers | None = Field(None, alias="Manufacturers")
    active: bool | None = Field(None, alias="Active")
    """
    Indicates whether this is an active programmable device.
    """
    primary: bool | None = Field(None, alias="Primary")
    """
    Indicates whether this is the primary active programmable device.
    """
    data_file: str | None = Field(None, alias="DataFile")
    """
    The data file with JSON information specific to this device.
    """
    silkscreen_name: SilkscreenName | None = Field(None, alias="SilkscreenName")
    reference_designator: ReferenceDesignator = Field(alias="ReferenceDesignator")
    capacity_bytes: float | None = Field(None, alias="CapacityBytes")
    """
    The storage capacity for this device.
    """
    physical_signals: list[Signal] | None = Field(None, alias="PhysicalSignals")
    """
    Information about the physical signals for this device.
    """
    connected_buses: ReferencedBusList | None = Field(None, alias="ConnectedBuses")
    oem: dict[str, Any] | None = Field(None, alias="OEM")
    """
    Provides additional OEM-specific information for a device.
    """


class Devices(RootModel[list[Device]]):
    root: list[Device]
    """
    Information about active and passive hardware devices
    """


class Bridge(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    models: Models | None = Field(None, alias="Models")
    manufacturers: Manufacturers | None = Field(None, alias="Manufacturers")
    version: str = Field(alias="Version")
    """
    The version for this bridge.
    """
    silkscreen_name: SilkscreenName | None = Field(None, alias="SilkscreenName")
    reference_designator: ReferenceDesignator = Field(alias="ReferenceDesignator")
    linked_buses: ReferencedBusList | None = Field(None, alias="LinkedBuses")


class Segment(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    netlist_name: str | None = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this segment.
    """
    connected_devices: ConnectedDeviceList | None = Field(None, alias="ConnectedDevices")
    connectors: AttachedConnectorList | None = Field(None, alias="Connectors")
    muxes: list[MuX] | None = Field(None, alias="MUXes")
    """
    Information about I2C MUXes in this I2C segment.
    """
    bridges: list[Bridge] | None = Field(None, alias="Bridges")
    """
    Information about I2C bridges in this I2C segment.
    """


class BusesI2C(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    netlist_name: str | None = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this bus.
    """
    voltage_tenths_volts: int = Field(alias="VoltageTenthsVolts")
    """
    The voltage needed to drive this bus.
    """
    required_power_state: RequiredPowerState = Field(alias="RequiredPowerState")
    frequency_k_hz: int = Field(alias="FrequencyKHz")
    """
    The clock frequency for this bus.
    """
    description: str | None = Field(None, alias="Description")
    """
    A description of the intended usage for this bus.
    """
    segments: list[Segment] = Field(alias="Segments")
    """
    Information about I2C segments.
    """


class Bridge1(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    models: Models | None = Field(None, alias="Models")
    manufacturers: Manufacturers | None = Field(None, alias="Manufacturers")
    version: str = Field(alias="Version")
    """
    The version of USB supported by this USB bridge.
    """
    linked_buses: ReferencedBusList | None = Field(None, alias="LinkedBuses")


class Segment5(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    connected_devices: ConnectedDeviceList | None = Field(None, alias="ConnectedDevices")
    connectors: AttachedConnectorList | None = Field(None, alias="Connectors")
    muxes: list[MuX4] | None = Field(None, alias="MUXes")
    """
    Information about muxes for this USB bus.
    """
    hubs: list[Hub1] | None = Field(None, alias="Hubs")
    """
    Information about hubs for this USB bus segment.
    """
    bridges: list[Bridge1] | None = Field(None, alias="Bridges")
    """
    Information about bridges for this USB bus segment.
    """


class BusesUSB(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    identifier: NamedComponent = Field(alias="Identifier")
    alias: ComponentAlias | None = Field(None, alias="Alias")
    netlist_name: str | None = Field(None, alias="NetlistName")
    """
    The name used in the netlist for this bus.
    """
    supported_version: str = Field(alias="SupportedVersion")
    """
    The maximum supported USB version for this USB bus.
    """
    host_controller: HostController = Field(alias="HostController")
    """
    The entity that controls the bus.
    """
    voltage_tenths_volts: int = Field(alias="VoltageTenthsVolts")
    """
    The voltage needed to drive this USB bus.
    """
    required_power_state: RequiredPowerState = Field(alias="RequiredPowerState")
    description: str | None = Field(None, alias="Description")
    """
    A description of the intended usage for this bus.
    """
    segments: list[Segment5] = Field(alias="Segments")
    """
    Information about segments for this USB bus.
    """


class Connectors(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    socs: list[ConnectorsSOCs] | None = Field(None, alias="SOCs")
    memory_subsystems: list[ConnectorsMemorySubsystem] | None = Field(None, alias="MemorySubsystems")
    composites: list[ConnectorsComposite] | None = Field(None, alias="Composites")
    cooling_subsystems: list[ConnectorsCoolingSubsystem] | None = Field(None, alias="CoolingSubsystems")
    drives: list[ConnectorsDrive] | None = Field(None, alias="Drives")
    mxios: list[ConnectorsMxio] | None = Field(None, alias="Mxios")
    mpics: list[ConnectorsMpic] | None = Field(None, alias="Mpics")
    ocp_mezzanine_slots: list[ConnectorsOCPMezzanineSlot] | None = Field(None, alias="OCPMezzanineSlots")
    power_supplies: list[ConnectorsPowerSupply] | None = Field(None, alias="PowerSupplies")
    control_panels: list[ConnectorsControlPanel] | None = Field(None, alias="ControlPanels")
    pcie_cems: list[ConnectorsPCIeCEM] | None = Field(None, alias="PCIe_CEMs")
    power_distribution_board_managements: list[ConnectorsPowerDistributionBoardManagement] | None = Field(
        None, alias="PowerDistributionBoardManagements"
    )
    real_time_clock_batteries: list[ConnectorsRealTimeClockBattery] | None = Field(None, alias="RealTimeClockBatteries")
    fans: list[ConnectorsFan] | None = Field(None, alias="Fans")
    scis: list[ConnectorsSCI] | None = Field(None, alias="SCIs")
    intrusion_detection: list[ConnectorsIntrusionDetection] | None = Field(None, alias="IntrusionDetection")
    physical_us_bs: list[ConnectorsPhysicalUSB] | None = Field(None, alias="PhysicalUSBs")
    oem: list[ConnectorsOEM] | None = Field(None, alias="OEM")
    """
    Provides information for an OEM-specific connector.
    """


class Buses(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    displayport: list[BusesDisplayPort] | None = Field(None, alias="DisplayPort")
    espi: list[BusesESPI] | None = Field(None, alias="ESPI")
    i2c: list[BusesI2C] | None = Field(None, alias="I2C")
    i3c: list[BusesI3C] | None = Field(None, alias="I3C")
    jtag: list[BusesJTAG] | None = Field(None, alias="JTAG")
    ltpi: list[BusesLTPI] | None = Field(None, alias="LTPI")
    mpesti: list[BusesMPESTI] | None = Field(None, alias="MPESTI")
    ncsi_rbt: list[BusesNCSIRBT] | None = Field(None, alias="NCSI_RBT")
    pcie: list[BusesPCIe] | None = Field(None, alias="PCIe")
    peci: list[BusesPECI] | None = Field(None, alias="PECI")
    qspi: list[BusesQSPI] | None = Field(None, alias="QSPI")
    sgmii: list[BusesSGMII] | None = Field(None, alias="SGMII")
    spi: list[BusesSPI] | None = Field(None, alias="SPI")
    sgpio: list[BusesSGPIO] | None = Field(None, alias="SGPIO")
    uart: list[BusesUART] | None = Field(None, alias="UART")
    usb: list[BusesUSB] | None = Field(None, alias="USB")
    oem: list[dict[str, Any]] | None = Field(None, alias="OEM")
    """
    Provides information for an OEM-specific bus.
    """


class Component(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    component_class: ComponentClass = Field(alias="ComponentClass")
    """
    The type of hardware that this component represents.
    """
    component_subclass: str = Field(alias="ComponentSubclass")
    """
    The subtype of hardware that this component represents, such as DNO, FLW, or SDNO for an HPM.
    """
    vendor_id: Annotated[str, StringConstraints(pattern=r"^([a-fA-F0-9]){4}$")] = Field(alias="VendorID")
    """
    The vendor ID assigned by the manufacturer for this component.
    """
    unique_id: str = Field(alias="UniqueID")
    """
    A unique ID assigned by the manufacturer for this component, such as a PCIe DeviceID.
    """
    power_policy: PowerPolicy | None = Field(None, alias="PowerPolicy")
    """
    The minimum system power state in which the component can be powered for full operation.
    """
    maximum_power_watts: int | None = Field(None, alias="MaximumPowerWatts")
    """
    The maximum wattage that the component can draw when fully powered.
    """
    connectors: Connectors = Field(alias="Connectors")
    devices: Devices = Field(alias="Devices")
    buses: Buses = Field(alias="Buses")


class HardwareComponent(BaseModel):
    model_config = ConfigDict(extra="forbid", use_attribute_docstrings=True)
    field_comment: str | None = Field(None, alias="_comment")
    """
    A general comment about a data file
    """
    copyright: str = Field(alias="Copyright")
    """
    A copyright statement for the FRU data.
    """
    version: str = Field(alias="Version")
    """
    The current file version for this FRU data.
    """
    schema_version: str = Field(alias="SchemaVersion")
    """
    The revision of the HardwareComponent schema that this FRU data was built against.
    """
    author: str = Field(alias="Author")
    """
    The author of this FRU data.
    """
    component: Component = Field(alias="Component")
    """
    Information about a hardware component.
    """


class Model(RootModel[HardwareComponent]):
    root: HardwareComponent
